name: Entertainment Apps on the Go with Windows 10
name_cn: Windows 10 娱乐应用便携指南
slug: entertainment-apps-on-the-go-with-windows-10
toc:
- - '#'
  - 目录
- - '##'
  - 引言
- - '##'
  - 内容概览
- - '##'
  - 作者简介与技术审校者简介
- - '###'
  - 作者简介
- - '###'
  - 技术审校者简介
- - '#'
  - 第 1 章 移动音乐服务
- - '##'
  - 1.1 使用 Groove 聆听音乐
- - '###'
  - 1.1.1 在 PC 或笔记本电脑上使用 Groove
- - '####'
  - 播放音乐
- - '####'
  - “全部”选项与音乐管理
- - '####'
  - 将内容固定到“开始”菜单
- - '####'
  - 购买歌曲与音乐订阅
- - '#####'
  - Groove Music Pass
- - '#####'
  - 管理你的设备
- - '######'
  - 探索音乐
- - '######'
  - 购买音乐
- - '######'
  - Groove 电台
- - '######'
  - 搜索音乐
- - '######'
  - 设置
- - '#######'
  - Music Pass
- - '#######'
  - 你的音乐
- - '###'
  - 1.1.2 在 Windows 10 Mobile 设备上使用 Groove
- - '####'
  - 播放音乐
- - '####'
  - 筛选与排序
- - '###'
  - 1.1.3 在 Android 设备和 iPhone 上使用 Groove
- - '####'
  - Android 设备
- - '#####'
  - 离线播放
- - '#####'
  - 广播
- - '####'
  - 设置
- - '###'
  - 1.1.4 在 iPhone 或 iPad 上使用 Groove
- - '####'
  - 离线播放
- - '####'
  - 广播
- - '####'
  - 设置
- - '##'
  - 1.2 在 Windows 10 上使用 Google Music
- - '##'
  - 1.3 在平板电脑和笔记本电脑上使用 iTunes Music
- - '##'
  - 1.4 从 iTunes 等应用向 Windows 10 手机传输音乐
- - '##'
  - 1.5 使用 TuneIn Radio 收听网络电台
- - '##'
  - 1.6 如何订阅播客
- - '###'
  - 在 Windows Phone 上
- - '###'
  - 在 Windows PC 上
- - '##'
  - 1.7 总结
- - '#'
  - 第 2 章 将音乐存储在云端
- - '##'
  - 2.1 使用 OneDrive 存储你的音乐
- - '##'
  - 2.2 使用 Google Play 存储音乐
- - '###'
  - 使用 Google 音乐管理器上传音乐
- - '###'
  - 使用 Google 音乐管理器下载音乐
- - '##'
  - 2.3 使用 Dropbox 存储你的音乐收藏
- - '##'
  - 2.4 通过 Xbox One 访问音乐
- - '###'
  - Now Playing
- - '###'
  - Groove Videos
- - '##'
  - 2.5 总结
- - '#'
  - 第 3 章 观看视频、电影和电视节目
- - '##'
  - 3.1 电影和电视应用
- - '###'
  - 观看已购买的电影和电视节目
- - '###'
  - 设置
- - '###'
  - 购买和租赁电影
- - '##'
  - 3.2 在 Windows 10 上使用 Netflix
- - '##'
  - 3.3 观看 YouTube 视频
- - '##'
  - 3.4 其它视频应用
- - '###'
  - VLC
- - '####'
  - 使用 VLC 播放音乐
- - '####'
  - 使用 VLC 播放视频
- - '####'
  - 文件管理器
- - '####'
  - 其他选项
- - '###'
  - 商店中的其他应用
- - '##'
  - 3.5 使用流量感知应用
- - '##'
  - 3.6 总结
- - '#'
  - 第 4 章 从 Windows 设备流式播放您的媒体收藏
- - '##'
  - 4.1 设置家庭组
- - '##'
  - 4.2 设置文件共享
- - '##'
  - 4.3 设置 Windows Media Player
- - '##'
  - 4.4 从 PC 访问存储在 Windows 7、8.1 和 10 上的内容
- - '###'
  - 使用家庭组访问媒体
- - '###'
  - 使用 Windows 10 访问共享文件夹
- - '###'
  - 将远程计算机文件夹添加到你的音乐和电影电视应用
- - '##'
  - 4.5 总结
- - '#'
  - 第 5 章 在家中流式传输媒体
- - '##'
  - 5.1 从 DLNA 服务器流式传输到 Windows PC
- - '###'
  - 流媒体音乐
- - '###'
  - 流媒体视频
- - '##'
  - 5.2 流式传输到 Windows 10 手机
- - '##'
  - 5.3 使用 Cast To 流式传输到 DLNA 设备
- - '###'
  - 在文件资源管理器中
- - '###'
  - 在 Windows Media Player 中
- - '###'
  - 将 Windows Media Player 作为媒体接收器
- - '###'
  - 从 Windows 10 手机流式传输
- - '###'
  - 使用电影和电视应用投射
- - '##'
  - 5.4 总结
- - '#'
  - 第 6 章 搭建媒体服务器以串流你的内容
- - '##'
  - 6.1 Plex 媒体服务器
- - '###'
  - 向 Plex 服务器添加音乐和视频
- - '###'
  - 通过浏览器从 Plex 媒体服务器串流到 PC
- - '####'
  - 播放音乐
- - '####'
  - 播放电影和电视节目
- - '###'
  - 在 PC 上通过 Plex 应用从 Plex 媒体服务器流式传输
- - '####'
  - 播放电影
- - '####'
  - 播放电视节目
- - '####'
  - 播放音乐
- - '###'
  - 使用 Plex 的 On Deck 功能
- - '##'
  - 6.2 在 Windows 10 手机上使用 Plex 应用进行流媒体播放
- - '###'
  - 播放电影
- - '###'
  - 播放电视节目
- - '###'
  - 播放音乐
- - '###'
  - 离线播放
- - '##'
  - 6.3 Emby Server 入门
- - '###'
  - 安装 Emby Server
- - '##'
  - 6.4 在 Windows 10 上使用 Emby 观看和收听
- - '###'
  - 播放电影
- - '###'
  - 播放电视节目
- - '###'
  - 播放音乐
- - '###'
  - 在 Windows 10 移动版上使用 Emby
- - '####'
  - 播放电影
- - '####'
  - 播放电视节目
- - '####'
  - 播放音乐
- - '###'
  - 使用网页浏览器使用 Emby
- - '##'
  - 6.5 其他平台上配置媒体服务器的资源
- - '###'
  - Kodi
- - '###'
  - Media Portal
- - '##'
  - 6.6 总结
- - '#'
  - 后记
- - '##'
  - 索引
