name: Software Development with Go
name_cn: Go 软件开发
slug: software-development-with-go
toc:
- - '#'
  - 引言
- - '#'
  - 致谢
- - '#'
  - 关于作者 关于技术审阅者
- - '#'
  - 第一部分 系统编程
- - '##'
  - 第1章：系统调用
- - '###'
  - 源代码
- - '###'
  - 什么是系统调用？
- - '###'
  - C 语言中的系统调用
- - '###'
  - sys/unix 包
- - '###'
  - Go 语言中的系统调用
- - '###'
  - 小结
- - '##'
  - 第2章：使用 Go 语言进行系统调用
- - '###'
  - 源代码
- - '###'
  - Syscall 包
- - '####'
  - syscall 应用
- - '####'
  - 检查磁盘空间
- - '####'
  - 使用 syscall 的 Web 服务器
- - '###'
  - ELF 包
- - '####'
  - 高级 ELF 格式
- - '####'
  - 转储示例
- - '###'
  - /sys 文件系统
- - '####'
  - 读取 AppArmor
- - '###'
  - 总结
- - '##'
  - 第3章：访问 proc 文件系统
- - '###'
  - 源代码
- - '###'
  - 窥探 procfs
- - '####'
  - 读取内存信息
- - '####'
  - 窥探网络信息
- - '###'
  - 使用 procfs 库
- - '####'
  - 代码示例
- - '####'
  - 了解 procfs 库的内部机制
- - '###'
  - 总结
- - '#'
  - 第二部分 容器
- - '##'
  - 第4章：简单容器
- - '###'
  - Linux 命名空间
- - '###'
  - cgroups
- - '###'
  - rootfs
- - '###'
  - Gontainer 项目
- - '###'
  - 总结
- - '##'
  - 第5章：带网络功能的容器
- - '###'
  - 源代码
- - '###'
  - 网络命名空间
- - '###'
  - 使用 ip 工具进行设置
- - '####'
  - 设置网桥 IP
- - '####'
  - 设置虚拟以太网并将其链接到命名空间
- - '####'
  - 启动虚拟以太网
- - '####'
  - 打印网络链接信息
- - '####'
  - 设置虚拟以太网并将其链接到命名空间
- - '####'
  - 启动虚拟以太网
- - '####'
  - 打印网络链接信息
- - '####'
  - 为不同的虚拟接口设置 IP 地址
- - '####'
  - 在 iptables 中注册网桥以允许转发
- - '###'
  - 带有网络的容器
- - '####'
  - 总结
- - '##'
  - 第6章：Docker 安全
- - '###'
  - 源代码
- - '###'
  - seccomp 配置文件
- - '####'
  - libseccomp
- - '####'
  - Docker seccomp
- - '###'
  - Docker 代理
- - '####'
  - 使用代理进行 Docker 通信
- - '###'
  - 容器攻击面
- - '###'
  - 本章小结
- - '#'
  - 第三部分：应用程序安全
- - '##'
  - 第7章：Gosec 与 AST
- - '###'
  - 源代码
- - '###'
  - 抽象语法树
- - '####'
  - 模块
- - '####'
  - 示例代码
- - '#####'
  - 检查（Inspecting）
- - '#####'
  - 解析文件
- - '###'
  - gosec
- - '####'
  - gosec 内部机制
- - '####'
  - 规则
- - '###'
  - 本章小结
- - '##'
  - 第8章：评分卡
- - '####'
  - 源代码
- - '###'
  - 什么是 Scorecard？
- - '####'
  - 设置 Scorecard
- - '####'
  - 运行 Scorecard
- - '####'
  - 高层流程
- - '###'
  - GitHub
- - '####'
  - GitHub API
- - '###'
  - GitHub Explorer
- - '###'
  - 总结
- - '#'
  - 第四部分 网络
- - '##'
  - 第9章：简单网络
- - '###'
  - 源代码
- - '###'
  - TCP 网络
- - '####'
  - TCP 客户端
- - '####'
  - TCP 服务器
- - '###'
  - UDP 网络
- - '####'
  - UDP 客户端
- - '####'
  - UDP 服务器
- - '####'
  - 并发服务器
- - '####'
  - 负载测试
- - '###'
  - 总结
- - '##'
  - 第10章：系统网络
- - '###'
  - 源代码
- - '###'
  - Ping 工具
- - '####'
  - 代码详解
- - '###'
  - DNS 服务器
- - '####'
  - 运行 DNS 服务器
- - '####'
  - DNS 转发器
- - '####'
  - 打包与解包
- - '###'
  - 总结
- - '##'
  - 第11章：Google gopacket
- - '###'
  - 源代码
- - '###'
  - gopacket
- - '####'
  - Layer
- - '#####'
  - TCP Layer
- - '####'
  - Packet
- - '###'
  - 使用 gopacket
- - '####'
  - pcap
- - '#####'
  - 安装 libpcap
- - '####'
  - 网络嗅探器
- - '####'
  - 代码解析
- - '####'
  - 手动分析 pcap 文件
- - '####'
  - 使用 WireShark 分析 pcap
- - '####'
  - 使用 BPF 进行捕获
- - '###'
  - 总结
- - '##'
  - 第12章：Epoll 库
- - '###'
  - 源代码
- - '###'
  - 理解 epoll
- - '###'
  - Golang 中的 epoll
- - '####'
  - Epoll 注册
- - '####'
  - Epoll 等待
- - '###'
  - Epoll 库
- - '####'
  - 总结
- - '#'
  - 第五部分 保障 Linux 安全
- - '##'
  - 第13章：漏洞扫描器
- - '###'
  - 源代码
- - '###'
  - 漏洞扫描器
- - '###'
  - 使用 Vuls
- - '####'
  - 检出代码
- - '####'
  - 运行扫描
- - '###'
  - 从 Vuls 中学习
- - '####'
  - 端口扫描
- - '####'
  - Exec
- - '####'
  - SQLite
- - '###'
  - 总结
- - '##'
  - 第14章：CrowdSec
- - '###'
  - 源代码
- - '###'
  - CrowdSec 项目
- - '####'
  - 使用 CrowdSec
- - '####'
  - crowdsec.db
- - '###'
  - 从 CrowdSec 中学习
- - '####'
  - 系统信号处理
- - '####'
  - 处理服务依赖关系
- - '####'
  - GeoIP 数据库
- - '###'
  - 本章小结
- - '#'
  - 第六部分 终端用户界面
- - '##'
  - 第15章：ANSI 与用户界面
- - '####'
  - 源代码
- - '###'
  - ANSI 转义码
- - '###'
  - 基于 ANSI 的 UI
- - '####'
  - 颜色表
- - '####'
  - 文本样式设置
- - '###'
  - 开源库
- - '####'
  - Gookit
- - '####'
  - Spinner
- - '###'
  - 总结
- - '##'
  - 第16章：TUI 框架
- - '###'
  - '`uiprogress`'
- - '####'
  - 代码流程
- - '####'
  - 更新进度
- - '###'
  - '`bubbletea`'
- - '####'
  - Init
- - '####'
  - Update
- - '####'
  - View
- - '###'
  - 总结
- - '#'
  - 第七部分 Linux 系统
- - '##'
  - 第17章：systemd
- - '####'
  - 源代码
- - '###'
  - systemd
- - '###'
  - systemd 单元 (Units)
- - '###'
  - systemctl
- - '####'
  - 你好，服务器系统守护进程（systemd）
- - '####'
  - go-systemd 库
- - '#####'
  - 查询服务
- - '###'
  - 日志
- - '###'
  - 机器
- - '###'
  - 小结
- - '##'
  - 第18章：cAdvisor
- - '###'
  - 源代码
- - '###'
  - 运行 cAdvisor
- - '###'
  - Web 用户界面
- - '###'
  - 架构
- - '###'
  - 初始化
- - '###'
  - 管理器
- - '###'
  - 监控文件系统
- - '###'
  - 来自 `/sys` 和 `/proc` 的信息
- - '###'
  - 客户端库
- - '###'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
