name: TouchDevelop
name_cn: TouchDevelop
slug: touchdevelop
toc:
- - '#'
  - 前言
- - '##'
  - 本书读者对象
- - '##'
  - 本书背景
- - '##'
  - 其他学习资料
- - '##'
  - 致谢
- - '#'
  - 目录
- - '##'
  - 图片列表
- - '##'
  - 表格列表
- - '#'
  - 第 1 章 TouchDevelop 简介
- - '##'
  - 电脑渴望被编程
- - '##'
  - 什么是 TouchDevelop？
- - '##'
  - TouchDevelop 生态系统
- - '###'
  - 历史与未来
- - '###'
  - 平台
- - '####'
  - 在 Windows Phone 上安装 TouchDevelop
- - '####'
  - 在其他平台上运行 TouchDevelop
- - '##'
  - 脚本语言
- - '#'
  - 第 2 章 脚本语言
- - '##'
  - 引言 – 语言风格
- - '###'
  - 示例程序（`/okzc`）
- - '##'
  - 数据类型和变量
- - '###'
  - '`Invalid` 值'
- - '###'
  - '`Nothing` 类型'
- - '###'
  - 值类型
- - '####'
  - '`Number`'
- - '####'
  - '`String`'
- - '###'
  - 引用类型
- - '####'
  - API 提供的引用类型
- - '##'
  - 集合类型
- - '###'
  - 表与索引
- - '###'
  - 对象
- - '###'
  - 装饰器
- - '###'
  - 全局持久化数据
- - '###'
  - 艺术项目
- - '###'
  - 表达式
- - '##'
  - 常量
- - '###'
  - 显式常量
- - '###'
  - 命名常量
- - '###'
  - 无效值
- - '##'
  - 变量
- - '###'
  - 局部变量
- - '###'
  - 全局数据变量
- - '###'
  - 操作参数
- - '###'
  - 运算符
- - '###'
  - 调用操作
- - '###'
  - 调用 API 方法
- - '##'
  - 语句
- - '###'
  - 表达式
- - '###'
  - 声明和赋值
- - '###'
  - If 语句
- - '###'
  - While 循环
- - '###'
  - For 循环
- - '###'
  - For each 循环
- - '##'
  - 操作
- - '###'
  - 定义动作
- - '####'
  - 公有与私有
- - '###'
  - 调用与返回
- - '###'
  - 输入参数
- - '###'
  - 结果参数
- - '###'
  - 调用库动作
- - '####'
  - 重新绑定库
- - '####'
  - 可见性
- - '##'
  - 事件
- - '##'
  - 页面
- - '##'
  - 创建库脚本
- - '###'
  - 对库的实现限制
- - '#'
  - 第 3 章 墙 – 使用屏幕
- - '##'
  - 3.1 输出 – 墙上的文字
- - '###'
  - 3.1.1 简单值的输出
- - '###'
  - 3.1.2 输出的方向
- - '###'
  - 3.1.3 复合值的输出
- - '###'
  - 3.1.4 媒体值的输出
- - '###'
  - 3.1.5 社交值的输出
- - '###'
  - 3.1.6 Web 值的输出
- - '##'
  - 3.2 从触控屏输入值
- - '##'
  - 3.3 更新 Wall 的内容
- - '###'
  - 可更新的文本框
- - '###'
  - 更新看板显示
- - '##'
  - 触摸屏事件
- - '###'
  - 点击墙面事件
- - '###'
  - 点击看板事件
- - '####'
  - 表 3-5：点击墙面事件
- - '##'
  - 页面推送与弹出
- - '###'
  - 标题和副标题
- - '###'
  - 3.7 墙上按钮
- - '###'
  - 3.8 按需生成输出
- - '#'
  - 第 4 章 网络
- - '##'
  - 4.1 网址与网页
- - '###'
  - 4.1.1 使用 URL
- - '###'
  - 4.1.2 创建和使用网络链接
- - '####'
  - 在墙面上使用网络链接
- - '###'
  - 4.1.3 检查互联网连接
- - '##'
  - 4.2 下载和上传文件
- - '###'
  - 4.2.1 下载文本文件或 HTML
- - '###'
  - 4.2.2 下载图片
- - '###'
  - 4.2.3 下载声音和音乐
- - '###'
  - 4.2.4 上传字符串和文件
- - '##'
  - 4.3 下载结构化数据
- - '###'
  - 4.3.1 以 JSON 格式下载信息
- - '###'
  - 4.3.2 以 XML 格式下载信息
- - '##'
  - 4.4 REST 指南与 Web 请求
- - '#'
  - 第 5 章 音频
- - '##'
  - 5.1 音乐
- - '###'
  - 5.1.1 处理歌曲集合
- - '###'
  - 5.1.2 获取单首歌曲（所有设备均可用）
- - '###'
  - 5.1.3 播放单首歌曲
- - '###'
  - 5.1.4 示例脚本
- - '##'
  - 5.2 声音
- - '##'
  - 5.3 麦克风
- - '#'
  - 第 6 章 摄像头、图形和视频
- - '##'
  - 6.1 摄像头
- - '###'
  - 6.1.1 示例程序
- - '##'
  - 6.2 处理图片
- - '###'
  - 6.2.1 图片集与图片集合（Windows Phone 和 Android）
- - '###'
  - 6.2.2 在其他设备上访问图片
- - '###'
  - 6.2.3 操作图片
- - '####'
  - 使用 `at`、`pixel` 和 `set pixel` 方法的注意事项
- - '####'
  - 图片着色效果
- - '####'
  - 图片叠加
- - '##'
  - 6.3 静态图形绘制与显示
- - '##'
  - 6.4 播放网络视频
- - '#'
  - 第 7 章 传感器
- - '##'
  - 7.1 传感器
- - '##'
  - 7.2 传感器驱动的事件
- - '###'
  - 7.2.1 示例脚本：计步器 (/jbpv)
- - '##'
  - 7.3 加速度计
- - '###'
  - 7.3.1 加速度力的方向
- - '###'
  - 7.3.2 示例脚本：灯光秀（`/tbcb`）
- - '##'
  - 7.4 指南针
- - '###'
  - 7.4.1 示例脚本：磁罗盘（`/drvu`）
- - '##'
  - 7.5 陀螺仪
- - '##'
  - 7.6 运动
- - '#'
  - 第 8 章 交互
- - '##'
  - 8.1 社交消息
- - '###'
  - 8.1.1 处理消息
- - '###'
  - 8.1.2 消息集合
- - '##'
  - 8.2 位置、地点、地图
- - '##'
  - 8.3 电子邮件
- - '##'
  - 8.4 电话呼叫
- - '##'
  - 8.5 二维条码
- - '##'
  - 8.6 短信消息（仅限 WP8）
- - '##'
  - 8.7 日历与约会（仅限 WP8）
- - '##'
  - 8.8 联系人（仅限 WP8 和 Android）
- - '#'
  - 第 9 章 游戏板
- - '##'
  - 9.1 简介
- - '###'
  - 9.1.1 什么是 Sprite？
- - '###'
  - 9.1.2 坐标与单位
- - '###'
  - 9.1.3 游戏程序结构
- - '##'
  - 9.2 Board 数据类型
- - '###'
  - 9.2.1 创建精灵
- - '###'
  - 9.2.2 障碍物与边界
- - '###'
  - 9.2.3 力与动画
- - '####'
  - 重力与摩擦力
- - '####'
  - 弹簧与锚点
- - '##'
  - 9.3 `Sprite` 数据类型
- - '###'
  - 视觉属性
- - '###'
  - 位置与运动
- - '###'
  - 加速度、力与弹跳
- - '###'
  - 9.3.1 管理精灵
- - '##'
  - 9.4 `精灵集合` 数据类型
- - '##'
  - 9.5 触摸与板子事件
- - '###'
  - 9.5.1 板子触摸操作
- - '###'
  - 9.5.2 `游戏循环` 事件
- - '###'
  - 9.5.3 `tap board` 事件
- - '###'
  - 9.5.4 `swipe board` 事件
- - '###'
  - 9.5.5 `tap sprite in XXX` 事件
- - '###'
  - 9.5.6 `swipe sprite in XXX` 事件
- - '###'
  - 9.5.7 `drag sprite in XXX` 事件
- - '###'
  - 9.5.8 `tap sprite SSS`、`swipe sprite SSS`、`drag sprite SSS`
- - '##'
  - 9.6 调试游戏
- - '#'
  - 第 10 章 使用框和页面的用户界面
- - '##'
  - 10.1 页面概述
- - '##'
  - 10.2 盒子概述
- - '##'
  - 10.3 盒子和页面的示例
- - '###'
  - 10.3.1 页面示例 1 (`/bvhugenw`)
- - '###'
  - 10.3.2 页面示例 2 (`/hnimxaiw`)
- - '###'
  - 10.3.3 页面示例 3 (`/wrsonnwh`)
- - '##'
  - 10.4 使用页面
- - '###'
  - 10.4.1 进入和离开页面
- - '###'
  - 10.4.2 编码限制
- - '##'
  - 10.5 用户界面的实时编辑
- - '##'
  - 框与页面的 API 支持
- - '###'
  - 表 10-3：`box` 服务的布局方法
- - '###'
  - 表 10-2：`box` 服务的文本处理方法
- - '###'
  - 表 10-1：`box` 服务的通用方法
- - '#'
  - 第 11 章 认证 Web 服务
- - '##'
  - 注册您的应用
- - '##'
  - 11.2 身份验证
- - '##'
  - 11.3 库
- - '##'
  - 11.4 高级主题
- - '###'
  - 11.4.1 唯一重定向 URI
- - '###'
  - 11.4.2 重定向 URI 中的状态变量
- - '#'
  - 附录 A 编辑 TouchDevelop 脚本
- - '##'
  - A.1 起点
- - '##'
  - A.2 编辑步骤
- - '###'
  - 开始操作 – 提供一个输入参数
- - '###'
  - 向操作中添加第一条语句
- - '###'
  - 添加第二条和第三条语句
- - '###'
  - 插入 `if` 语句
- - '###'
  - 定义游戏循环事件
- - '###'
  - 尝试运行脚本
- - '##'
  - A.3 附加步骤
- - '###'
  - 修订脚本
- - '###'
  - 发布脚本
- - '##'
  - A.4 更多高级编辑功能
- - '###'
  - A.4.1 将代码重构为新的操作
- - '###'
  - A.4.2 复制和粘贴代码
- - '###'
  - A.4.3 用高级别结构包围代码
- - '#'
  - 附录 B TouchDevelop 服务
- - '###'
  - B.1 集市
- - '##'
  - B.2 `box`
- - '##'
  - B.3 `collections`
- - '##'
  - B.4 `colors`
- - '##'
  - B.5 `contract`
- - '##'
  - B.6 `invalid`
- - '##'
  - B.7 语言
- - '##'
  - B.8 位置
- - '##'
  - B.9 地图
- - '##'
  - B.10 `math`
- - '##'
  - B.11 `media`
- - '##'
  - B.12 `phone`
- - '##'
  - B.13 `player`
- - '##'
  - B.14 传感器
- - '##'
  - B.15 社交
- - '##'
  - B.16 标签
- - '##'
  - B.17 磁贴
- - '##'
  - B.18 时间
- - '###'
  - B.19 墙面
- - '###'
  - B.20 网络
- - '#'
  - 附录 C TouchDevelop 数据类型
- - '##'
  - C.1 日历约会
- - '##'
  - C.2 日历约会集合
- - '##'
  - C.3 游戏面板
- - '##'
  - C.4 布尔值
- - '##'
  - C.5 摄像头
- - '##'
  - C.6 颜色
- - '##'
  - C.7 联系人
- - '###'
  - 联系人类型的获取方法
- - '###'
  - 联系人类型的设置方法
- - '###'
  - 联系人类型的其他方法
- - '##'
  - C.8 联系人集合
- - '##'
  - C.9 日期时间
- - '###'
  - 日期时间类型的获取方法
- - '###'
  - 日期时间类型的其他方法
- - '##'
  - C.10 表单生成器
- - '##'
  - C.11 Json 生成器
- - '##'
  - C.12 JSON 对象
- - '##'
  - C.13 链接
- - '##'
  - C.14 链接集合
- - '##'
  - C.15 位置
- - '##'
  - C.16 位置集合
- - '##'
  - C.17 地图
- - '##'
  - C.18 `Matrix`
- - '##'
  - C.19 `Message`
- - '###'
  - '`Message` 类型的 Get 方法'
- - '###'
  - '`Message` 类型的 Set 方法'
- - '###'
  - '`Message` 类型的其他方法'
- - '##'
  - C.20 `Message Collection`
- - '##'
  - C.21 `Motion`
- - '##'
  - C.22 `Number`
- - '##'
  - C.23 `数字集合`
- - '##'
  - C.24 `数字映射`
- - '##'
  - C.25 `OAuth 响应`
- - '##'
  - C.26 `页面`
- - '##'
  - C.27 `页面按钮`
- - '##'
  - C.28 `页面集合`
- - '###'
  - C.29 图片（Picture）
- - '###'
  - C.30 图片相册（Picture Album）
- - '###'
  - C.31 图片相册集合（Picture Albums）
- - '###'
  - C.32 图片集合（Pictures）
- - '###'
  - C.33 地点（Place）
- - '###'
  - C.34 地点集合（Place Collection）
- - '###'
  - C.35 播放列表
- - '###'
  - C.36 播放列表集合
- - '###'
  - C.37 歌曲
- - '###'
  - C.38 歌曲集合
- - '###'
  - C.39 歌曲专辑
- - '###'
  - C.40 歌曲专辑集合
- - '###'
  - C.41 歌曲集合（Song Collection）
- - '###'
  - C.42 音效
- - '###'
  - C.43 精灵
- - '###'
  - 精灵类型的其他方法
- - '##'
  - C.44 精灵集合
- - '##'
  - C.45 字符串
- - '##'
  - C.46 字符串集合
- - '##'
  - C.47 字符串映射
- - '##'
  - C.48 `TextBox`
- - '##'
  - C.49 `Vector3`
- - '##'
  - C.50 `Web Request`
- - '##'
  - C.51 `Web Response`
- - '##'
  - C.52 `Xml Object`
- - '#'
  - 附录 D 平台能力
- - '###'
  - D.1 支持的浏览器
- - '###'
  - D.2 通用功能
- - '###'
  - D.3 支持的传感器与设备
- - '###'
  - D.4 服务/资源支持
- - '###'
  - D.5 对已创建应用的支持
- - '####'
  - D.5.1 适用于 Windows Phone 商店的应用
- - '####'
  - D.5.2 适用于 Windows 商店的应用
- - '#'
  - 附录 E Windows Phone 上的 TouchDevelop 编辑器
- - '###'
  - E.1 示例程序
- - '###'
  - E.2 返回按钮、撤销与错误
- - '###'
  - E.3 编辑示例
- - '###'
  - 开始使用
- - '###'
  - main 操作中的第二行代码
- - '####'
  - main 操作中的第三行代码
- - '###'
  - 开始使用 if 语句
- - '###'
  - if 语句的 'then' 子句
- - '###'
  - if 语句的 else 子句
- - '###'
  - main 操作的最后一条语句
- - '###'
  - gameloop 事件
- - '###'
  - 尝试运行脚本
- - '##'
  - E.4 附加步骤
- - '###'
  - 修改脚本
- - '###'
  - 发布脚本
- - '###'
  - 缺少按钮？
- - '###'
  - 将代码重构为新的操作
- - '#'
  - 索引
- - '###'
  - 符号
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J, K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X
- - '###'
  - Y
- - '###'
  - Z
