name: Beginning Go Programming
name_cn: Go 编程入门指南
slug: beginning-go-programming
toc:
- - '#'
  - 1. 简介
- - '##'
  - GoLang 是静态类型还是编译型语言？
- - '###'
  - 编译型编程语言
- - '###'
  - 静态类型语言
- - '##'
  - Go 是一门面向对象的编程语言吗？
- - '##'
  - 使 GoLang 成为编程首选的功能特性
- - '##'
  - GoLang 有意排除的功能特性
- - '##'
  - Go 程序
- - '##'
  - 摘要
- - '#'
  - 2. Go 基础
- - '##'
  - Go 的起源
- - '##'
  - Go 语法
- - '##'
  - 安装 Go
- - '##'
  - Go Playground
- - '##'
  - 使用 IDE 开发 Go 应用程序
- - '##'
  - 开始编写 Go 应用程序入门
- - '###'
  - 让我们打印 Hello World！
- - '####'
  - 如何执行 Go 程序
- - '####'
  - 关键字
- - '###'
  - 变量
- - '####'
  - 变量数据类型
- - '####'
  - 变量命名约定
- - '####'
  - 声明变量
- - '###'
  - 获取用户输入
- - '####'
  - 使用 scanf
- - '####'
  - 使用 Scanln
- - '####'
  - 使用 bufio
- - '##'
  - 数学运算符与包
- - '###'
  - Math 包
- - '####'
  - 日期与时间
- - '####'
  - Go 中的运算符优先级
- - '##'
  - 内存管理与引用值
- - '###'
  - New 与 Make 的区别
- - '###'
  - 错误的内存分配示例
- - '###'
  - 正确的内存分配示例
- - '###'
  - 内存释放
- - '##'
  - 指针数据类型
- - '###'
  - 什么是指针？
- - '###'
  - 在 Go 中声明指针
- - '###'
  - 与 Java 及 C 风格语言的比较
- - '##'
  - 数组和切片中的有序值
- - '###'
  - Go 中的数组
- - '####'
  - 声明数组
- - '####'
  - 初始化数组
- - '####'
  - 访问数组元素
- - '####'
  - 查询数组的大小
- - '###'
  - Go 中的切片
- - '####'
  - 定义切片
- - '####'
  - '`len()` 和 `cap()` 函数'
- - '####'
  - nil 切片
- - '####'
  - Go 中的子切片操作
- - '####'
  - '`append()` 和 `copy()` 函数'
- - '####'
  - 排序切片
- - '##'
  - 映射
- - '###'
  - 定义映射
- - '###'
  - 向映射对象添加条目
- - '###'
  - 从映射对象中删除条目
- - '###'
  - 遍历映射对象中存储的值
- - '##'
  - 结构体数据类型
- - '###'
  - 定义结构体
- - '###'
  - 访问结构体的成员
- - '###'
  - 将结构体作为函数参数传递
- - '###'
  - 指向结构体的指针
- - '##'
  - 程序流程
- - '###'
  - If 语句
- - '##'
  - Switch 语句
- - '##'
  - For 语句
- - '##'
  - goto 语句
- - '##'
  - 函数
- - '###'
  - 定义函数
- - '###'
  - 在 Go 中执行函数调用
- - '###'
  - 从函数返回多个值
- - '###'
  - 向函数传递参数
- - '####'
  - 传值示例
- - '####'
  - 传引用示例
- - '###'
  - 方法
- - '##'
  - 读写文本文件
- - '###'
  - 写入文本文件
- - '###'
  - 读取文本文件
- - '##'
  - HTTP 包
- - '##'
  - JSON
- - '##'
  - 总结
- - '#'
  - 3. Go 实战方案：编程基础与入门
- - '##'
  - Go 中的数字与切片
- - '##'
  - Go 中的映射操作
- - '##'
  - Go 的错误处理方式
- - '##'
  - 延迟与恐慌恢复
- - '###'
  - 动手挑战
- - '###'
  - 解决方案
- - '##'
  - 总结
- - '#'
  - 4. 处理文本
- - '##'
  - Go 字符串格式化与 Unicode 处理
- - '###'
  - Go 中的不区分大小写比较
- - '###'
  - 使用 Go 进行正则表达式和读取文本文件
- - '###'
  - 动手挑战
- - '###'
  - 解决方案
- - '###'
  - 小结
- - '#'
  - 5. 结构体、方法与接口
- - '##'
  - Go 语言中的结构体、方法与接口
- - '###'
  - 结构体
- - '####'
  - 在 Go 语言中声明结构体
- - '####'
  - 创建结构体类型的实例
- - '###'
  - 结构体实战解析
- - '###'
  - 方法
- - '####'
  - 在 Go 中声明方法
- - '####'
  - 方法实战解析
- - '###'
  - 接口
- - '####'
  - 在 Go 中声明接口
- - '####'
  - 在 Go 中实现接口
- - '####'
  - 接口实战示例
- - '##'
  - 空接口与 Go 语言中的 IOTA 使用
- - '###'
  - JSON 编码/解码
- - '###'
  - 泛型
- - '###'
  - 动手挑战
- - '###'
  - 解决方案
- - '###'
  - 总结
- - '#'
  - 6. 使用 JSON 工作
- - '##'
  - JSON 包
- - '##'
  - 使用 Go 语言解析 JSON
- - '##'
  - 使用 Go 语言解析复杂 JSON
- - '##'
  - 使用 Go 语言生成 JSON
- - '##'
  - 处理 JSON 中的缺失值与零值
- - '###'
  - 使用 `mapstructure` 处理任意 JSON
- - '##'
  - 总结
- - '#'
  - 7. HTTP
- - '##'
  - Go 与 HTTP 调用
- - '##'
  - 在 Go 语言中编写 HTTP 服务器与身份验证
- - '##'
  - 使用 `gorilla/mux` 实现 REST
- - '###'
  - 动手挑战
- - '###'
  - 解决方案
- - '##'
  - 格式化结果
- - '##'
  - 总结
- - '#'
  - 8. 并发
- - '##'
  - 理解 Goroutines
- - '###'
  - 将顺序代码转换为并发代码
- - '##'
  - 使用带有共享资源的 Goroutines
- - '###'
  - 查看共享资源对协程的影响
- - '###'
  - 使用互斥锁访问共享资源
- - '###'
  - 使用原子计数器修改共享资源
- - '##'
  - 同步协程
- - '###'
  - '`sync.WaitGroup` 与 `sync.Once`'
- - '##'
  - Go 语言中的超时处理
- - '##'
  - Goroutine 池化
- - '###'
  - 动手挑战
- - '###'
  - 解决方案
- - '##'
  - 总结
- - '#'
  - 9. 技巧与实用窍门
- - '##'
  - 导入包
- - '##'
  - 检查应用程序导入了哪些包
- - '##'
  - 使用 `goimports` 代替 `gofmt`
- - '##'
  - 代码组织
- - '##'
  - 使用还是不用：自定义构造函数
- - '##'
  - 将代码模块化并组织成包
- - '##'
  - 依赖包管理
- - '##'
  - 编译器优化
- - '##'
  - 使用 Git 的 SHA 设置构建 ID
- - '##'
  - 优雅常量的案例，即 IOTA
- - '###'
  - 自动递增
- - '###'
  - 自定义类型
- - '###'
  - 跳过值
- - '###'
  - 表达式
- - '###'
  - 易混淆的常量
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K
- - '##'
  - L
- - '##'
  - M, N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V, W, X, Y, Z
