name: Generic data structures and algorithms in Go
name_cn: Go 通用数据结构和算法
slug: generic-data-structures-and-algorithms-in-go
toc:
- - '#'
  - 引言
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 关于技术审稿人
- - '#'
  - 第1章 Go 语言泛型与并发初览
- - '##'
  - 1.1 Go 语言简史与概述
- - '##'
  - 1.2 泛型参数介绍
- - '###'
  - 按姓名添加新学生
- - '###'
  - 按 ID 号添加新学生
- - '###'
  - 通过 `Student` 结构体添加新生
- - '###'
  - 引入泛型
- - '###'
  - '`Stringer` 类型'
- - '###'
  - 受约束的泛型类型
- - '###'
  - 实现接口
- - '###'
  - 实例化泛型类型
- - '###'
  - 无约束的泛型类型 `any`
- - '###'
  - 泛型的优势
- - '###'
  - 使用 Go 的 sort 包
- - '###'
  - Sort Type
- - '###'
  - Map Functions
- - '###'
  - 使 MyMap 成为泛型
- - '###'
  - Filter Functions
- - '###'
  - 使 MyFilter 成为泛型
- - '##'
  - 1.3 并发
- - '###'
  - Goroutine
- - '###'
  - WaitGroup
- - '###'
  - Channel
- - '###'
  - Select 语句
- - '###'
  - 使用`quit`通道避免使用`WaitGroup`
- - '###'
  - 通道方向
- - '###'
  - 竞态条件
- - '###'
  - 互斥锁
- - '###'
  - 使用Goroutine下棋
- - '###'
  - 使用Goroutine计算斐波那契数列
- - '##'
  - 1.4 基准测试并发应用程序
- - '###'
  - 使用并发生成质数
- - '###'
  - 埃拉托斯特尼筛法算法
- - '###'
  - 分段筛算法
- - '###'
  - 并发筛法解决方案
- - '##'
  - 1.5 本章小结
- - '#'
  - 第2章 算法效率：排序与搜索
- - '##'
  - 2.1 描述算法的速度效率
- - '###'
  - 理解大 O
- - '###'
  - 判断数字切片是否已排序
- - '###'
  - 使用并发
- - '##'
  - 2.2 排序算法
- - '###'
  - 冒泡排序算法
- - '###'
  - 快速排序算法
- - '###'
  - 大 O 分析
- - '###'
  - 快速排序的最坏情况
- - '###'
  - 比较冒泡排序和快速排序
- - '###'
  - 并发快速排序
- - '###'
  - 归并排序算法
- - '###'
  - 并发归并排序
- - '###'
  - 结论
- - '##'
  - 2.3 搜索数组切片
- - '###'
  - 线性搜索
- - '###'
  - 并发搜索
- - '###'
  - 二分搜索
- - '##'
  - 2.4 小结
- - '#'
  - 第3章 抽象数据类型：Go 中没有类的面向对象编程
- - '##'
  - 3.1 使用类的抽象数据类型
- - '##'
  - 3.2 Go 语言中的抽象数据类型
- - '###'
  - ADT `Counter`
- - '###'
  - 创建 counter 包
- - '###'
  - 创建包的机制
- - '###'
  - 实现抽象数据类型的另一个示例
- - '###'
  - 使用组合（Composition）
- - '##'
  - 3.3 多态
- - '###'
  - 使用接口实现多态
- - '##'
  - 3.4 面向对象应用：简化版二十一点游戏
- - '##'
  - 3.5 另一个面向对象应用：单词排列组
- - '###'
  - 使用标准 `map` 数据结构
- - '##'
  - 3.6 总结
- - '#'
  - 第4章 ADT 实战：生命游戏
- - '##'
  - 4.1 游戏
- - '###'
  - 网格细胞演化规则
- - '##'
  - 4.2 网格的 ADT
- - '##'
  - 4.3 游戏的终端实现
- - '###'
  - '# # #'
- - '###'
  - '# # #'
- - '###'
  - '# # #'
- - '###'
  - '# # #'
- - '###'
  - '# # #'
- - '###'
  - '# # #'
- - '###'
  - '# # #'
- - '##'
  - 4.4 生命游戏的 GUI 实现
- - '###'
  - 创建 go.mod 文件
- - '###'
  - 程序输出
- - '##'
  - 4.5 总结
- - '#'
  - 第5章 栈
- - '##'
  - 5.1 栈 ADT
- - '##'
  - 5.2 通用栈的切片实现
- - '###'
  - GetZero 函数
- - '###'
  - 为什么 `T` 被声明为 `Ordered`
- - '##'
  - 5.3 泛型栈的节点实现
- - '##'
  - 5.4 比较节点栈与切片栈的效率
- - '##'
  - 5.5 栈的应用：函数求值
- - '###'
  - 后缀求值
- - '###'
  - 遍历算法
- - '###'
  - 计算后缀表达式
- - '##'
  - 5.6 将十进制数转换为二进制数
- - '##'
  - 5.7 迷宫应用
- - '###'
  - 使用栈的迷宫路径高效策略
- - '###'
  - 构建迷宫应用的基础设施
- - '###'
  - 完成的迷宫应用
- - '##'
  - 5.8 本章小结
- - '#'
  - 第6章 队列与列表
- - '##'
  - 6.1 队列 ADT
- - '##'
  - 6.2 切片队列的实现
- - '###'
  - 迭代器
- - '##'
  - 6.3 节点队列的实现
- - '##'
  - 6.4 比较切片队列和节点队列的性能
- - '##'
  - 6.5 双端队列
- - '##'
  - 6.6 Deque 应用
- - '##'
  - 6.7 优先队列
- - '##'
  - 6.8 队列应用：等待线的离散事件模拟
- - '###'
  - 泊松过程
- - '###'
  - 模拟逻辑
- - '###'
  - 系统实现
- - '###'
  - 队列应用：洗牌
- - '###'
  - 洗牌模型
- - '##'
  - 6.9 链表
- - '##'
  - 6.10 单向链表
- - '##'
  - 6.11 双向链表
- - '###'
  - 双向链接的优势
- - '##'
  - 6.12 总结
- - '#'
  - 第7章 哈希表
- - '##'
  - 7.1 `Map`
- - '###'
  - 哈希加密
- - '##'
  - 7.2 `Map` 有多快？
- - '##'
  - 7.3 构建哈希表
- - '###'
  - 创建一个空的哈希表
- - '###'
  - 向哈希表插入数据
- - '###'
  - 冲突与冲突解决
- - '###'
  - 负载因子
- - '###'
  - 判断键是否存在
- - '###'
  - 比较哈希表与标准 Map 的性能
- - '##'
  - 7.4 哈希应用：字符串搜索
- - '###'
  - 滚动哈希计算
- - '###'
  - Rabin-Karp 算法
- - '##'
  - 7.5 泛型集合
- - '##'
  - 7.6 小结
- - '#'
  - 第8章 二叉树
- - '##'
  - 8.1 二叉树
- - '##'
  - 8.2 树的遍历
- - '###'
  - 中序遍历
- - '###'
  - 前序遍历
- - '###'
  - 后序遍历
- - '##'
  - 8.3 绘制树
- - '###'
  - 二叉树结构
- - '###'
  - 用于显示二叉树的基础设施
- - '###'
  - 代码解释
- - '###'
  - ShowTreeGraph 的实现
- - '###'
  - 在 `binarytree` 和 `main` 子目录中创建 `go.mod` 文件
- - '##'
  - 8.4 总结
- - '#'
  - 第9章 二叉搜索树
- - '##'
  - 9.1 概述
- - '###'
  - 搜索
- - '###'
  - 插入
- - '###'
  - 有序输出
- - '###'
  - 删除
- - '##'
  - 9.2 通用二叉搜索树
- - '####'
  - 类型 `OrderedStringer`
- - '####'
  - 二叉搜索树所需的泛型类型
- - '####'
  - 二叉搜索树的方法
- - '####'
  - '`Insert`、`Delete` 和中序遍历的讨论'
- - '####'
  - 辅助函数
- - '###'
  - 树形图实现
- - '###'
  - 对 `binarysearchtree` 包和主驱动程序的讨论
- - '##'
  - 9.3 总结
- - '#'
  - 第10章 AVL 树
- - '##'
  - 10.1 概述：Adelson Velsky 与 Landis
- - '###'
  - 树的旋转
- - '###'
  - 插入
- - '###'
  - 删除
- - '###'
  - 关于 AVL 树的事实
- - '##'
  - 10.2 实现一个通用 AVL 树
- - '###'
  - '`avl` 包说明'
- - '###'
  - 主驱动程序结果讨论
- - '##'
  - 10.3 使用 Map、AVL 树和并发 AVL 树实现集合
- - '###'
  - 使用 Map、AVL 树和并发 AVL 树实现集合
- - '###'
  - 并发 AVL 集合的解释
- - '###'
  - 比较三种集合实现
- - '###'
  - 结果讨论
- - '##'
  - 10.4 本章小结
- - '#'
  - 第11章 堆树
- - '##'
  - 11.1 堆树的构建
- - '##'
  - 11.2 从堆树中删除
- - '##'
  - 11.3 堆树的实现
- - '###'
  - 构建堆树的逻辑
- - '###'
  - 包 `heap`
- - '###'
  - 包 `heap` 说明
- - '##'
  - 11.4 堆排序
- - '###'
  - 堆排序结果讨论
- - '##'
  - 11.5 堆的应用：优先队列
- - '##'
  - 11.6 本章小结
- - '#'
  - 第12章 红黑树
- - '##'
  - 12.1 红黑树
- - '###'
  - 红黑树的定义
- - '###'
  - 红黑树示例
- - '##'
  - 12.2 插入过程
- - '###'
  - 多次插入的详细演练
- - '##'
  - 12.3 红黑树的实现
- - '###'
  - 比较红黑树与 AVL 树的性能
- - '###'
  - 基准测试结论
- - '##'
  - 12.4 小结
- - '#'
  - 第13章 表达式树
- - '##'
  - 13.1 表达式树
- - '##'
  - 13.2 表达式树的构建
- - '###'
  - 构建一个新的表达式树
- - '###'
  - '`NewTree` 函数的解释'
- - '###'
  - 使用表达式树的函数求值
- - '###'
  - 方法 `Evaluate` 的说明
- - '##'
  - 13.3 `ShowTreeGraph` 的实现
- - '##'
  - 13.4 总结
- - '#'
  - 第14章 使用并发进行生态模拟
- - '##'
  - 14.1 概述
- - '##'
  - 14.2 规格说明
- - '###'
  - 鲭鱼
- - '###'
  - 金枪鱼
- - '###'
  - 鲨鱼
- - '###'
  - 输出
- - '##'
  - 14.3 设计
- - '##'
  - 14.4 实现
- - '###'
  - 每个物种的数据模型
- - '###'
  - 代码讨论
- - '###'
  - 支持函数
- - '###'
  - 代码讨论
- - '###'
  - 使鲭鱼符合 `MarineLife` 类型所需的方法
- - '###'
  - 代码讨论
- - '###'
  - 鲨鱼的移动方法
- - '###'
  - 代码讨论
- - '###'
  - 金枪鱼的移动方法
- - '###'
  - 生物图形化显示的输出函数
- - '###'
  - 代码讨论
- - '###'
  - 模拟的完整实现
- - '##'
  - 14.5 摘要
- - '#'
  - 第15章 动态规划
- - '##'
  - 15.1 动态规划示例：第 n 个斐波那契数
- - '###'
  - 自上而下的动态规划
- - '###'
  - 自下而上的动态规划
- - '###'
  - 递归解法
- - '###'
  - 代码讨论
- - '##'
  - 15.2 另一个应用：0/1 背包问题
- - '###'
  - 暴力解法
- - '###'
  - 代码讨论
- - '###'
  - 动态规划解法
- - '###'
  - 代码讨论
- - '###'
  - 代码讨论
- - '##'
  - 15.3 DNA 子序列
- - '###'
  - 代码讨论
- - '##'
  - 15.4 总结
- - '#'
  - 第16章 图结构
- - '##'
  - 16.1 表示图
- - '##'
  - 16.2 遍历图
- - '##'
  - 16.3 深度优先搜索与广度优先搜索
- - '###'
  - 深度优先搜索
- - '###'
  - 广度优先搜索
- - '##'
  - 16.4 图中的单源最短路径
- - '###'
  - 实现
- - '###'
  - 解答说明
- - '##'
  - 16.5 最小生成树
- - '###'
  - 克鲁斯卡尔算法
- - '##'
  - 16.6 克鲁斯卡尔算法的实现
- - '###'
  - Kruskal 算法实现详解
- - '##'
  - 16.7 总结
- - '#'
  - 第17章 旅行商问题
- - '##'
  - 17.1 旅行商问题及其历史
- - '##'
  - 17.2 精确的蛮力解法
- - '###'
  - 寻找排列
- - '###'
  - 旅行商问题的暴力计算
- - '###'
  - 代码讨论
- - '###'
  - 其他解法
- - '##'
  - 17.3 显示 TSP 路径
- - '###'
  - 代码讨论
- - '##'
  - 17.4 小结
- - '#'
  - 第18章 旅行商问题的分支定界解法
- - '##'
  - 18.1 用于 TSP 的分支定界法
- - '###'
  - 一个示例
- - '###'
  - 下界计算
- - '###'
  - 分支定界算法
- - '###'
  - 优先队列
- - '###'
  - 遍历前面提到的五城示例的一部分
- - '##'
  - 18.2 分支定界法的实现
- - '###'
  - 优先队列的实现
- - '###'
  - 生成分支定界解
- - '###'
  - main 函数的数据
- - '###'
  - 结果
- - '##'
  - 18.3 总结
- - '#'
  - 第19章 模拟退火：一种解决 TSP 的启发式解法
- - '##'
  - 19.1 组合优化
- - '###'
  - 启发式解法
- - '##'
  - 19.2 模拟退火
- - '###'
  - 模拟退火步骤
- - '###'
  - 收敛到局部最小值而非全局最小值的问题
- - '##'
  - 19.3 模拟退火算法的实现
- - '###'
  - 代码讨论
- - '###'
  - 结果
- - '###'
  - 显示最终结果
- - '###'
  - 交叉的线段
- - '##'
  - 19.4 总结
- - '#'
  - 第20章 TSP 的遗传算法
- - '##'
  - 20.1 遗传算法
- - '###'
  - 遗传算法的高级描述
- - '###'
  - 遗传算法的更详细描述
- - '##'
  - 20.2 遗传算法的实现
- - '###'
  - 步骤 1 – 形成随机路径的初始种群
- - '###'
  - 步骤 2 – 形成最优路径精英组
- - '###'
  - 步骤 3 – 锦标赛选择
- - '###'
  - 步骤 4 – 父本交配
- - '###'
  - 形成下一代
- - '###'
  - 整合所有模块
- - '##'
  - 20.3 本章小结
- - '#'
  - 第21章 神经网络与机器学习
- - '##'
  - 21.1 神经网络与机器学习概述
- - '###'
  - 训练
- - '###'
  - 神经网络
- - '###'
  - 感知器
- - '###'
  - 神经网络示意图
- - '###'
  - 神经元
- - '##'
  - 21.2 一个具体示例
- - '##'
  - 21.3 构建神经网络
- - '###'
  - 表示网络的矩阵
- - '##'
  - 21.4 神经网络实现
- - '###'
  - 估算成本关于每个权重的偏导数
- - '##'
  - 21.5 神经网络输出
- - '##'
  - 21.6 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T, U, V
- - '##'
  - W, X, Y, Z
