name: Network Programming with Go Language
name_cn: Go 语言网络编程
slug: network-programming-with-go-language
toc:
- - '#'
  - 第二版前言
- - '#'
  - 第一版前言
- - '#'
  - 致谢
- - '#'
  - 关于作者 关于技术审校者
- - '#'
  - 架构层次
- - '##'
  - 协议层
- - '###'
  - ISO OSI 协议
- - '###'
  - OSI 层
- - '###'
  - TCP/IP 协议
- - '###'
  - 其他替代协议
- - '##'
  - 网络
- - '##'
  - 网关
- - '##'
  - 主机级网络
- - '#'
  - 数据包封装
- - '#'
  - 连接模型
- - '##'
  - 面向连接
- - '##'
  - 无连接
- - '#'
  - 通信模型
- - '##'
  - 消息传递
- - '##'
  - 远程过程调用
- - '#'
  - 分布式计算模型
- - '##'
  - 客户端-服务器系统
- - '##'
  - 客户端-服务器应用
- - '##'
  - 服务器分布
- - '##'
  - 通信流
- - '###'
  - 同步通信
- - '###'
  - 异步通信
- - '###'
  - 流式通信
- - '###'
  - 发布/订阅
- - '##'
  - 组件分布
- - '###'
  - 高德纳分类法
- - '####'
  - 示例：分布式数据库
- - '####'
  - 示例：网络文件服务
- - '####'
  - 示例：万维网
- - '####'
  - 示例：终端仿真
- - '####'
  - 示例：安全外壳
- - '###'
  - 三层模型
- - '###'
  - 胖与瘦
- - '##'
  - 中间件模型
- - '###'
  - 中间件示例
- - '###'
  - 中间件功能
- - '##'
  - 处理连续体
- - '#'
  - 失效点
- - '#'
  - 验收因素
- - '#'
  - 关于分布式计算的思考
- - '##'
  - 透明性
- - '###'
  - 访问透明性
- - '###'
  - 位置透明性
- - '###'
  - 迁移透明性
- - '###'
  - 复制透明性
- - '###'
  - 并发透明性
- - '###'
  - 可扩展性透明性
- - '###'
  - 性能透明性
- - '###'
  - 故障透明性
- - '##'
  - 分布式计算的八个谬误
- - '###'
  - '*谬误：* 网络是可靠的'
- - '###'
  - 谬误：延迟为零
- - '###'
  - 谬误：带宽无限
- - '###'
  - 谬误：网络是安全的
- - '###'
  - 谬误：拓扑结构不变
- - '###'
  - 谬误：只有一个管理员
- - '###'
  - 谬误：传输成本为零
- - '###'
  - 谬误：网络是同质的
- - '##'
  - 结论
- - '#'
  - 2. Go 语言概述
- - '##'
  - 类型
- - '###'
  - 切片与数组
- - '###'
  - 映射
- - '###'
  - 指针
- - '###'
  - 函数
- - '###'
  - 结构体
- - '##'
  - 方法
- - '##'
  - 多线程
- - '##'
  - 包
- - '##'
  - 模块
- - '##'
  - 类型转换
- - '##'
  - 语句
- - '##'
  - GOPATH
- - '##'
  - 运行 Go 程序
- - '##'
  - 标准库
- - '##'
  - 错误值
- - '##'
  - 结论
- - '#'
  - 3. 套接字编程
- - '##'
  - TCP/IP 协议栈
- - '###'
  - IP 数据报
- - '###'
  - UDP
- - '###'
  - TCP
- - '##'
  - 互联网地址
- - '###'
  - IPv4 地址
- - '###'
  - IPv6 地址
- - '##'
  - IP 地址类型
- - '##'
  - 使用现有文档和示例
- - '###'
  - IPMask 类型
- - '####'
  - 基本路由
- - '####'
  - IPAddr 类型
- - '####'
  - 主机规范名称和地址查找
- - '##'
  - 服务
- - '###'
  - 端口
- - '####'
  - TCPAddr 类型
- - '##'
  - TCP 套接字
- - '###'
  - TCP 客户端
- - '##'
  - 白天时间服务器
- - '##'
  - 多线程服务器
- - '##'
  - 控制 TCP 连接
- - '###'
  - 超时
- - '###'
  - 保持连接
- - '##'
  - UDP 数据报
- - '###'
  - 服务器监听多个套接字
- - '###'
  - Conn、PacketConn 和 Listener 类型
- - '##'
  - 原始套接字与 `IPConn` 类型
- - '##'
  - 结论
- - '#'
  - 4. 数据序列化
- - '##'
  - 结构化数据
- - '###'
  - 共同协定
- - '###'
  - 自描述数据
- - '###'
  - 编码包
- - '##'
  - ASN.1
- - '###'
  - ASN.1 白天时间客户端与服务器
- - '##'
  - JSON
- - '###'
  - 客户端与服务器
- - '##'
  - Gob 包
- - '###'
  - 一个客户端和一个服务器
- - '##'
  - 将二进制数据编码为字符串
- - '##'
  - 代码示例与协议缓冲
- - '###'
  - Protocol Buffers
- - '####'
  - 安装与编译 Protocol Buffers
- - '####'
  - 生成的 personv3.pb.go 文件
- - '####'
  - 使用生成的代码
- - '##'
  - 结论
- - '#'
  - 5. 应用层协议
- - '##'
  - 协议设计
- - '##'
  - 为什么你应该关心
- - '##'
  - 版本控制
- - '##'
  - 万维网
- - '##'
  - 消息格式
- - '###'
  - 数据格式
- - '####'
  - 字节格式
- - '####'
  - 字符格式
- - '##'
  - 一个简单的示例
- - '###'
  - 独立应用程序
- - '###'
  - 客户端-服务器应用程序
- - '###'
  - 客户端
- - '###'
  - 备选的表示层方面
- - '###'
  - 服务器端
- - '###'
  - 协议：非正式版
- - '###'
  - 文本协议
- - '##'
  - 服务器代码
- - '##'
  - 客户端代码
- - '##'
  - Textproto 包
- - '##'
  - 状态信息
- - '###'
  - 应用状态转换图
- - '###'
  - 客户端状态转换图
- - '###'
  - 服务器端状态转换图
- - '###'
  - 服务器伪代码
- - '##'
  - 结论
- - '#'
  - 6. 管理字符集与编码
- - '##'
  - 定义
- - '###'
  - 字符
- - '###'
  - 字符库/字符集
- - '###'
  - 字符代码
- - '###'
  - 字符编码
- - '###'
  - 传输编码
- - '##'
  - ASCII
- - '##'
  - ISO 8859
- - '##'
  - Unicode
- - '###'
  - UTF-8、Go 与 Rune
- - '####'
  - UTF-8 客户端与服务器
- - '####'
  - ASCII 客户端与服务器
- - '###'
  - UTF-16 与 Go
- - '####'
  - 小端序与大端序
- - '####'
  - UTF-16 客户端与服务器
- - '##'
  - Unicode 注意事项
- - '##'
  - ISO 8859 与 Go
- - '##'
  - 其他字符集与 Go
- - '##'
  - 结论
- - '#'
  - 7. 安全
- - '#'
  - ISO 安全架构
- - '##'
  - 功能与层级
- - '##'
  - 机制
- - '##'
  - 数据完整性
- - '##'
  - 对称密钥加密
- - '###'
  - 公钥加密
- - '##'
  - X.509 证书
- - '###'
  - TLS
- - '####'
  - 基础客户端
- - '####'
  - 使用自签名证书的服务器
- - '##'
  - 总结
- - '#'
  - 8. HTTP
- - '##'
  - URL 和资源
- - '###'
  - i18n
- - '###'
  - HTTP 特性
- - '###'
  - 版本
- - '####'
  - HTTP/0.9
- - '#####'
  - 响应格式
- - '####'
  - HTTP/1.0
- - '#####'
  - 请求格式
- - '#####'
  - 响应格式
- - '####'
  - HTTP 1.1
- - '####'
  - HTTP 主要版本升级
- - '####'
  - HTTP/2
- - '####'
  - HTTP/3
- - '##'
  - 简单用户代理
- - '###'
  - 响应类型
- - '###'
  - HEAD 方法
- - '###'
  - GET 方法
- - '##'
  - 配置 HTTP 请求
- - '###'
  - 客户端对象
- - '##'
  - 代理处理
- - '###'
  - 简单代理
- - '###'
  - 认证代理
- - '##'
  - 客户端的 HTTPS 连接
- - '###'
  - 服务器端
- - '####'
  - 文件服务器
- - '####'
  - 处理函数
- - '####'
  - 绕过默认多路复用器
- - '##'
  - HTTPS
- - '##'
  - 结论
- - '#'
  - 9. 模板
- - '##'
  - 插入对象值
- - '###'
  - 使用模板
- - '###'
  - 管道
- - '##'
  - 定义函数
- - '##'
  - 变量
- - '###'
  - 条件语句
- - '##'
  - html/template 包
- - '##'
  - 总结
- - '#'
  - 10. 完整的 Web 服务器
- - '##'
  - 浏览器界面示意图
- - '##'
  - 浏览器端文件
- - '##'
  - 基础服务器
- - '###'
  - listFlashCards 函数
- - '###'
  - manageFlashCards 函数
- - '##'
  - 中文词典
- - '###'
  - 词典类型
- - '###'
  - 闪卡组
- - '###'
  - 修复音调
- - '###'
  - ListWords 函数
- - '##'
  - '`showFlashCards` 函数'
- - '###'
  - 浏览器中的呈现
- - '###'
  - 运行服务器
- - '##'
  - 总结
- - '#'
  - 11. HTML
- - '##'
  - '`html/template` 包'
- - '##'
  - HTML 词法分析
- - '##'
  - XHTML/HTML
- - '##'
  - JSON
- - '##'
  - 结论
- - '#'
  - 12. XML
- - '##'
  - 解组 XML
- - '##'
  - 编组 XML
- - '##'
  - 解析 XML
- - '###'
  - StartElement 类型
- - '###'
  - EndElement 类型
- - '###'
  - CharData 类型
- - '###'
  - Comment 类型
- - '###'
  - ProcInst 类型
- - '###'
  - Directive 类型
- - '##'
  - XHTML
- - '##'
  - HTML
- - '##'
  - 结论
- - '#'
  - 13. 远程过程调用
- - '##'
  - Go 语言的 RPC
- - '###'
  - HTTP RPC 服务器
- - '###'
  - HTTP RPC 客户端
- - '###'
  - TCP RPC 服务器
- - '###'
  - TCP RPC 客户端
- - '###'
  - 值的匹配
- - '##'
  - JSON
- - '###'
  - JSON RPC 服务器
- - '###'
  - JSON RPC 客户端
- - '##'
  - 结论
- - '#'
  - 14. REST
- - '##'
  - URI 与资源
- - '##'
  - 表述（Representations）
- - '##'
  - REST 动词（REST Verbs）
- - '###'
  - GET 动词
- - '###'
  - PUT 动词
- - '###'
  - DELETE 动词
- - '###'
  - POST 动词
- - '###'
  - 不维护状态（即无状态）
- - '###'
  - HATEOAS
- - '##'
  - 表示链接
- - '##'
  - 使用 REST 进行事务处理
- - '###'
  - 表 14-2 现有 RESTful 事务模型分析
- - '###'
  - 表 14-1 RESTful 事务模型
- - '##'
  - 理查森成熟度模型
- - '###'
  - 第 0 级
- - '###'
  - 第 1 级：资源
- - '###'
  - 第 2 级：HTTP 动词
- - '###'
  - 第 3 级：超媒体控制
- - '##'
  - 再谈闪卡系统
- - '###'
  - 回顾
- - '###'
  - URL
- - '###'
  - ServeMux（多路复用器）
- - '##'
  - 内容协商
- - '###'
  - GET /
- - '###'
  - POST /
- - '###'
  - 处理其他 URL
- - '##'
  - 完整服务器
- - '##'
  - 客户端
- - '##'
  - 使用 REST 还是 RPC
- - '##'
  - 结论
- - '#'
  - 15. WebSocket
- - '##'
  - WebSocket 服务器
- - '##'
  - '`golang.org/x/net/websocket` 包'
- - '###'
  - 消息对象
- - '###'
  - JSON 对象
- - '###'
  - 编解码器类型
- - '###'
  - 基于 TLS 的 WebSocket
- - '###'
  - HTML 页面中的 WebSocket
- - '##'
  - '`github.com/gorilla/websocket` 包'
- - '###'
  - 回声服务器
- - '###'
  - Echo 客户端
- - '##'
  - 结论
- - '#'
  - 16. Gorilla
- - '##'
  - 中间件模式
- - '##'
  - 标准库 ServeMux 示例
- - '##'
  - 自定义多路复用器
- - '##'
  - '`gorilla/mux`'
- - '##'
  - 为什么要关注
- - '##'
  - Gorilla 处理器
- - '##'
  - 更多 Gorilla 示例
- - '###'
  - '`gorilla/rpc`'
- - '###'
  - '`gorilla/schema`'
- - '###'
  - '`gorilla/securecookie`'
- - '##'
  - 结论
- - '#'
  - 17. 测试
- - '##'
  - 简洁与缺陷
- - '##'
  - '`httptest` 包'
- - '##'
  - HTTP 层以下
- - '##'
  - 善用标准库
- - '##'
  - 结论
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E, F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K
- - '##'
  - L
- - '##'
  - M, N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
