name: Kubernetes Programming with Go
name_cn: Go Kubernetes 编程指南
slug: kubernetes-programming-with-go
toc:
- - '#'
  - 引言
- - '#'
  - 章节概览
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 关于技术审阅者
- - '#'
  - 1. Kubernetes API 简介
- - '##'
  - Kubernetes 平台概览
- - '##'
  - OpenAPI 规范
- - '##'
  - 动词与种类
- - '##'
  - 组-版本-资源
- - '##'
  - 子资源
- - '##'
  - 官方 API 参考文档
- - '###'
  - 部署文档
- - '###'
  - 操作文档
- - '###'
  - Pod 文档
- - '###'
  - 文档的单页版本
- - '##'
  - 总结
- - '#'
  - 2. Kubernetes API 操作
- - '##'
  - 检查请求
- - '##'
  - 发起请求
- - '###'
  - 使用 `kubectl` 作为代理
- - '###'
  - 创建资源
- - '###'
  - 获取资源信息
- - '###'
  - 获取资源列表
- - '####'
  - 集群范围
- - '####'
  - 在特定命名空间中
- - '###'
  - 过滤列表结果
- - '###'
  - 使用标签选择器
- - '###'
  - 使用字段选择器
- - '###'
  - 删除资源
- - '###'
  - 删除资源集合
- - '###'
  - 更新资源
- - '###'
  - 管理更新资源时的冲突
- - '###'
  - 使用策略合并补丁更新资源
- - '####'
  - 修补数组字段
- - '####'
  - 特殊指令
- - '#####'
  - '`replace` 指令'
- - '#####'
  - '`delete` 指令'
- - '#####'
  - '`deleteFromPrimitiveList` 指令'
- - '#####'
  - '`setElementOrder` 指令'
- - '###'
  - 在服务端应用资源
- - '####'
  - deploy.yaml
- - '###'
  - 监听资源
- - '###'
  - 在监听会话期间进行过滤
- - '###'
  - 列出资源后进行监听
- - '###'
  - 重启 *监听* 请求
- - '###'
  - 允许使用书签高效重启 `watch` 请求
- - '###'
  - 分页结果
- - '####'
  - 完整列表的一致性
- - '####'
  - 检测最后一个数据块
- - '##'
  - 以各种格式获取结果
- - '###'
  - 以表格形式获取结果
- - '####'
  - 列定义
- - '####'
  - 行数据
- - '###'
  - 使用 YAML 格式
- - '###'
  - 使用 Protobuf 格式
- - '##'
  - 结论
- - '#'
  - 3. 在 Go 中使用 API 资源
- - '##'
  - API 库源码与导入
- - '##'
  - 包的内容
- - '###'
  - types.go
- - '###'
  - register.go
- - '###'
  - doc.go
- - '###'
  - generated.pb.go 和 generated.proto
- - '###'
  - types\_swagger\_doc\_generated.go
- - '###'
  - zz\_generated.deepcopy.go
- - '##'
  - core/v1 中的特定内容
- - '###'
  - ObjectReference
- - '###'
  - ResourceList
- - '###'
  - Taint
- - '###'
  - Toleration
- - '###'
  - Well-Known Labels
- - '##'
  - Writing Kubernetes Resources in Go
- - '###'
  - 导入包
- - '###'
  - '`TypeMeta` 字段'
- - '###'
  - '`ObjectMeta` 字段'
- - '####'
  - Name
- - '####'
  - Namespace
- - '####'
  - UID、ResourceVersion 和 Generation
- - '####'
  - 标签与注解
- - '###'
  - 设置 APIVersion 和 Kind
- - '####'
  - 设置 Controller
- - '####'
  - 设置 BlockOwnerDeletion
- - '###'
  - 规范与状态
- - '###'
  - 与编写 YAML 清单的比较
- - '##'
  - 完整示例
- - '##'
  - 总结
- - '#'
  - 4. 使用通用类型
- - '##'
  - 指针
- - '###'
  - 获取值的引用
- - '###'
  - 解引用指针
- - '###'
  - 比较两个引用的值
- - '##'
  - 数量
- - '###'
  - 将字符串解析为数量
- - '###'
  - 使用 inf.Dec 作为数量
- - '###'
  - 使用缩放整数作为数量
- - '###'
  - 数量的运算
- - '##'
  - IntOrString
- - '##'
  - Time
- - '###'
  - 工厂方法
- - '###'
  - Time 上的操作
- - '##'
  - 总结
- - '#'
  - 5. API Machinery
- - '##'
  - Schema 包
- - '##'
  - Scheme
- - '###'
  - 初始化
- - '###'
  - 映射
- - '###'
  - 转换
- - '####'
  - 添加转换函数
- - '####'
  - 执行转换
- - '###'
  - 序列化
- - '####'
  - JSON 和 YAML 序列化器
- - '####'
  - Protobuf 序列化器
- - '###'
  - 编码与解码
- - '##'
  - RESTMapper
- - '###'
  - Kind 到 Resource 的映射
- - '###'
  - Resource 到 Kind 的映射
- - '###'
  - 查找资源
- - '###'
  - DefaultRESTMapper 实现
- - '##'
  - 总结
- - '#'
  - 6. `Client-go` 库
- - '##'
  - 连接到集群
- - '###'
  - 集群内配置
- - '###'
  - 集群外配置
- - '####'
  - 从内存中的 Kubeconfig 文件构建
- - '####'
  - 从磁盘上的 Kubeconfig 文件构建
- - '####'
  - 从个性化的 Kubeconfig 文件构建
- - '####'
  - 从多个 Kubeconfig 文件构建
- - '####'
  - 使用 CLI 标志覆盖 kubeconfig
- - '##'
  - 获取 Clientset
- - '##'
  - 使用 Clientset
- - '##'
  - 检查请求
- - '##'
  - 创建资源
- - '##'
  - 获取资源信息
- - '##'
  - 获取资源列表
- - '##'
  - 过滤列表结果
- - '###'
  - 使用 Labels 包设置 LabelSelector
- - '####'
  - 使用 Requirements
- - '####'
  - 解析 LabelSelector 字符串
- - '####'
  - 使用一组键值对
- - '###'
  - 使用 Fields 包设置 FieldSelector
- - '####'
  - 组合单项选择器
- - '####'
  - 解析 FieldSelector 字符串
- - '####'
  - 使用一组键值对
- - '##'
  - 删除资源
- - '##'
  - 删除资源集合
- - '##'
  - 更新资源
- - '###'
  - 使用战略性合并补丁更新资源
- - '##'
  - 使用 Patch 进行服务端应用
- - '###'
  - 使用应用配置进行服务端应用
- - '####'
  - 从头构建 ApplyConfiguration
- - '####'
  - 从现有资源构建 ApplyConfiguration
- - '##'
  - 监控资源
- - '##'
  - 错误和状态
- - '###'
  - '`metav1.Status` 结构的定义'
- - '###'
  - 客户端集操作返回的错误
- - '###'
  - RESTClient
- - '###'
  - 构建请求
- - '###'
  - 执行请求
- - '###'
  - 利用 Result
- - '###'
  - 以表格形式获取结果
- - '##'
  - 发现客户端
- - '##'
  - RESTMapper
- - '###'
  - PriorityRESTMapper
- - '###'
  - DeferredDiscoveryRESTMapper
- - '#'
  - 总结
- - '#'
  - 7. 使用 Client-go 测试应用程序
- - '##'
  - Fake Clientset
- - '###'
  - 检查函数结果
- - '###'
  - 对操作作出反应
- - '###'
  - 检查 Actions
- - '##'
  - 伪造 REST 客户端
- - '##'
  - FakeDiscovery 客户端
- - '###'
  - 存根 ServerVersion
- - '###'
  - 动作
- - '###'
  - 模拟资源
- - '##'
  - 结论
- - '#'
  - 8. 使用自定义资源定义扩展 Kubernetes API
- - '##'
  - 在 Go 中执行操作
- - '##'
  - 深入了解 CustomResourceDefinition
- - '###'
  - 命名资源
- - '###'
  - 资源版本的定义
- - '###'
  - 版本间转换
- - '##'
  - 资源的架构
- - '###'
  - 部署自定义资源定义
- - '##'
  - 附加打印列(Additional Printer Columns)
- - '##'
  - 结论
- - '#'
  - 9. 使用自定义资源
- - '##'
  - 生成 Clientset
- - '###'
  - 使用 `deepcopy-gen`
- - '####'
  - 安装 `deepcopy-gen`
- - '####'
  - 添加注解
- - '####'
  - 运行 `deepcopy-gen`
- - '###'
  - 使用 `client-gen`
- - '####'
  - 安装 `client-go`
- - '####'
  - 添加注解
- - '###'
  - 添加 `AddToScheme` 函数
- - '###'
  - 运行 `client-gen`
- - '###'
  - 使用生成的客户端集
- - '###'
  - 使用生成的 *fake* 客户端集
- - '##'
  - 使用 `Unstructured` 包和动态客户端
- - '###'
  - '`Unstructured` 类型'
- - '####'
  - 访问 `TypeMeta` 字段的获取方法和设置方法
- - '####'
  - 访问 `ObjectMeta` 字段的获取方法和设置方法
- - '####'
  - 用于创建和转换的方法
- - '###'
  - 访问非元字段的辅助函数
- - '####'
  - 示例
- - '###'
  - '`UnstructuredList` 类型'
- - '####'
  - 访问 `TypeMeta` 字段的 Getter 和 Setter
- - '####'
  - 访问 `ListMeta` 字段的 Getter 和 Setter
- - '####'
  - 用于创建和转换的方法
- - '###'
  - 在类型化对象与非结构化对象之间转换
- - '###'
  - 动态客户端
- - '####'
  - 获取动态客户端
- - '####'
  - 使用动态客户端
- - '####'
  - 示例
- - '####'
  - '*模拟* 动态客户端'
- - '##'
  - 总结
- - '#'
  - 10. 使用 `controller-runtime` 库编写操作器
- - '##'
  - 管理器
- - '##'
  - 控制器
- - '###'
  - 创建控制器
- - '###'
  - 监视资源
- - '##'
  - 第一个示例
- - '##'
  - 使用控制器构建器
- - '###'
  - 使用 `ControllerBuilder` 的第二个示例
- - '###'
  - 向 Reconciler 注入 Manager 资源
- - '####'
  - 在创建 Reconciler 结构体时传递值
- - '####'
  - 使用注入器
- - '##'
  - 使用客户端（Client）
- - '###'
  - 获取资源信息
- - '###'
  - 列出资源
- - '##'
  - 创建资源
- - '##'
  - 删除资源
- - '##'
  - 删除资源集合
- - '##'
  - 更新资源
- - '##'
  - 修补资源
- - '###'
  - 服务端应用（Server-side Apply）
- - '###'
  - 策略合并补丁（Strategic Merge Patch）
- - '###'
  - 合并补丁（Merge Patch）
- - '##'
  - 更新资源的状态（Status）
- - '###'
  - 修补资源的状态
- - '##'
  - 日志记录（Logging）
- - '###'
  - 详细程度（Verbosity）
- - '###'
  - 预定义值（Predefined Values）
- - '###'
  - 日志记录器名称（Logger Name）
- - '###'
  - 从上下文中获取日志记录器
- - '##'
  - 事件
- - '##'
  - 结论
- - '#'
  - 11. 编写调谐循环
- - '##'
  - 编写 Reconcile 函数
- - '###'
  - 检查资源是否存在
- - '###'
  - 实现已调和资源
- - '###'
  - 简单实现示例
- - '##'
  - 结论
- - '#'
  - 12. 测试调谐循环
- - '##'
  - envtest 包
- - '###'
  - 安装 envtest 二进制文件
- - '###'
  - 使用 envtest
- - '###'
  - 定义 Ginkgo 测试套件
- - '##'
  - 编写测试
- - '###'
  - 测试 1
- - '###'
  - 测试 2
- - '###'
  - 测试 3
- - '###'
  - 测试 4
- - '##'
  - 总结
- - '#'
  - 13. 使用 Kubebuilder 创建 Operator
- - '###'
  - 安装 Kubebuilder
- - '###'
  - 创建项目
- - '##'
  - 向项目添加自定义资源
- - '##'
  - 构建和部署 Manifest 文件
- - '##'
  - 本地运行 Manager
- - '##'
  - 个性化自定义资源
- - '###'
  - 编辑 Go 结构体
- - '###'
  - 启用 Status 子资源
- - '###'
  - 定义打印机列
- - '###'
  - 重新生成文件
- - '###'
  - 实现 Reconcile 函数
- - '###'
  - 添加 RBAC 注解
- - '###'
  - 在集群上部署 Operator
- - '###'
  - 创建资源的新版本
- - '####'
  - 定义新版本
- - '###'
  - 实现 Hub 和 Convertible
- - '###'
  - 设置 Webhook
- - '###'
  - 更新 Kustomization 文件
- - '###'
  - 使用不同版本
- - '##'
  - 结论
- - '#'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I， J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P， Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W， X
- - '###'
  - Y, Z
