name: Pro Go
name_cn: Go 高级指南
slug: pro-go
toc:
- - '#'
  - 第一部分 理解 Go 语言
- - '#'
  - 第 1 章 你的第一个 Go 应用程序
- - '##'
  - 场景设定
- - '##'
  - 安装开发工具
- - '###'
  - 安装 Git
- - '###'
  - 选择代码编辑器
- - '##'
  - 创建项目
- - '###'
  - partyinvites
- - '###'
  - 定义数据类型与集合
- - '###'
  - 创建 HTML 模板
- - '####'
  - 加载模板
- - '####'
  - 标题层级调整
- - '##'
  - 创建 HTTP 处理程序和服务器
- - '##'
  - 编写表单处理函数
- - '###'
  - 处理表单数据
- - '##'
  - 添加数据验证
- - '##'
  - 本章小结
- - '#'
  - 第 2 章 将 Go 置于上下文中
- - '##'
  - 为什么要学习 Go？
- - '###'
  - “坑”在哪儿？
- - '###'
  - 真的那么糟糕吗？
- - '###'
  - 你需要了解什么？
- - '##'
  - 本书结构是怎样的？
- - '###'
  - 第 1 部分：理解 Go 语言
- - '###'
  - 第 2 部分：使用 Go 标准库
- - '###'
  - 第 3 部分：应用 Go
- - '##'
  - 本书未涵盖哪些内容？
- - '##'
  - 如果你在书中发现错误怎么办？
- - '##'
  - 示例多吗？
- - '##'
  - 运行示例需要什么软件？
- - '##'
  - 示例将在哪些平台上运行？
- - '##'
  - 如果遵循示例时遇到问题怎么办？
- - '##'
  - 我在哪里可以获取示例代码？
- - '##'
  - 为什么有些示例的格式很奇怪？
- - '##'
  - 如何联系作者？
- - '##'
  - 如果我很喜欢这本书，该怎么办？
- - '##'
  - 如果这本书让我感到愤怒并想投诉，该怎么办？
- - '##'
  - 本章小结
- - '#'
  - 第 3 章 使用 Go 工具
- - '##'
  - 使用 `go` 命令
- - '##'
  - 创建 Go 项目
- - '###'
  - 理解包声明
- - '###'
  - 理解导入语句
- - '###'
  - 理解函数
- - '###'
  - 理解代码语句
- - '##'
  - 在 Go 代码中使用分号
- - '##'
  - 编译并运行源代码
- - '###'
  - 配置 Go 编译器
- - '###'
  - 清理
- - '###'
  - 使用 Go Run 命令
- - '###'
  - 定义模块
- - '##'
  - 调试 Go 代码
- - '###'
  - 使用 Println 函数进行调试
- - '###'
  - 准备调试
- - '###'
  - 使用调试器
- - '####'
  - 使用 Delve 编辑器插件
- - '##'
  - Linting Go 代码
- - '###'
  - 使用 Linter
- - '###'
  - 理解 Go 文档
- - '###'
  - 禁用 Linter 规则
- - '###'
  - 创建 Linter 配置文件
- - '###'
  - 在代码编辑器中进行 Lint 检查
- - '##'
  - 修复 Go 代码中的常见问题
- - '###'
  - _/C_/tools
- - '###'
  - _/C_/tools {
- - '####'
  - 了解每个分析器的功能
- - '##'
  - 格式化 Go 代码
- - '##'
  - 本章小结
- - '#'
  - 第 4 章 基本类型、值和指针
- - '##'
  - 本章准备工作
- - '###'
  - 使用 Go 标准库
- - '##'
  - 了解基本数据类型
- - '###'
  - 理解字面量
- - '##'
  - 使用常量
- - '###'
  - 理解无类型常量
- - '####'
  - 理解 IOTA
- - '###'
  - 使用单个语句定义多个常量
- - '###'
  - 再探字面量
- - '##'
  - 使用变量
- - '###'
  - 省略变量的数据类型
- - '###'
  - 省略变量的值赋值
- - '###'
  - 使用单个语句定义多个变量
- - '###'
  - 使用短变量声明语法
- - '###'
  - 使用短变量语法重定义变量
- - '###'
  - 使用空白标识符
- - '##'
  - 理解指针
- - '###'
  - 理解指针算术
- - '####'
  - 定义指针
- - '###'
  - 跟随指针
- - '###'
  - 理解指针的零值
- - '###'
  - 指向指针的指针
- - '####'
  - 理解指针为何有用
- - '##'
  - 本章小结
- - '#'
  - 第 5 章 操作与类型转换
- - '###'
  - 本章准备工作
- - '##'
  - 理解 Go 语言运算符
- - '###'
  - 表 5-3 Go 语言基本运算符
- - '##'
  - 理解算术运算符
- - '###'
  - 表 5-4 算术运算符
- - '####'
  - 理解算术溢出
- - '###'
  - 使用取余运算符
- - '###'
  - 使用递增和递减运算符
- - '###'
  - 拼接字符串
- - '##'
  - 理解比较运算符
- - '####'
  - 比较指针
- - '##'
  - 理解逻辑运算符
- - '##'
  - 转换、解析和格式化值
- - '###'
  - 执行显式类型转换
- - '####'
  - 理解显式转换的局限性
- - '###'
  - 将浮点值转换为整数
- - '####'
  - 从字符串解析
- - '###'
  - 解析整数
- - '###'
  - 解析二进制、八进制和十六进制整数
- - '###'
  - 使用整数便捷函数
- - '####'
  - 解析浮点数
- - '###'
  - 将值格式化为字符串
- - '####'
  - 格式化布尔值
- - '####'
  - 格式化整数值
- - '####'
  - 使用整数便捷函数
- - '###'
  - 格式化浮点数值
- - '##'
  - 本章小结
- - '#'
  - 第 6 章 流程控制
- - '##'
  - 本章准备
- - '##'
  - 理解流程控制
- - '###'
  - 使用 if 语句
- - '##'
  - 关于流程控制语句语法的限制
- - '##'
  - 使用 else 关键字
- - '##'
  - 理解 if 语句的作用域
- - '###'
  - 在 `if` 语句中使用初始化语句
- - '##'
  - 使用 `for` 循环
- - '###'
  - 将条件整合到循环中
- - '###'
  - 使用初始化语句和完成语句
- - '###'
  - 循环的继续执行
- - '###'
  - 枚举序列
- - '####'
  - 枚举序列时仅接收索引或值
- - '####'
  - 枚举内置数据结构
- - '##'
  - 使用 switch 语句
- - '###'
  - 匹配多个值
- - '####'
  - 终止 `case` 语句的执行
- - '###'
  - 强制穿透到下一个 `case` 语句
- - '###'
  - 提供 `default` 子句
- - '###'
  - 使用初始化语句
- - '###'
  - 省略比较值
- - '##'
  - 使用标签语句
- - '##'
  - 总结
- - '#'
  - 第 7 章 使用数组、切片和映射
- - '##'
  - 本章准备
- - '###'
  - 处理数组
- - '##'
  - 使用数组字面量语法
- - '###'
  - 创建多维数组
- - '##'
  - 理解数组类型
- - '###'
  - 让编译器确定数组长度
- - '##'
  - 理解数组值
- - '###'
  - 比较数组
- - '###'
  - 枚举数组
- - '##'
  - 使用切片
- - '###'
  - 向切片追加元素
- - '####'
  - 分配额外的切片容量
- - '###'
  - 将一个切片追加到另一个切片
- - '###'
  - 从现有数组创建切片
- - '###'
  - 使用现有数组创建切片时追加元素
- - '###'
  - 让切片行为可预测
- - '###'
  - 从数组创建切片时指定容量
- - '###'
  - 从其他切片创建切片
- - '###'
  - 使用`copy`函数
- - '####'
  - 使用 `copy` 函数确保切片数组独立
- - '####'
  - 理解未初始化切片的陷阱
- - '####'
  - 复制切片时指定范围
- - '####'
  - 复制不同大小的切片
- - '###'
  - 删除切片元素
- - '###'
  - 枚举切片
- - '###'
  - 排序切片
- - '###'
  - 比较切片
- - '###'
  - 获取切片底层的数组
- - '##'
  - 使用映射
- - '###'
  - 使用映射字面量语法
- - '###'
  - 检查映射中的元素
- - '###'
  - 从映射中删除元素
- - '###'
  - 枚举映射的内容
- - '####'
  - 按顺序枚举映射
- - '###'
  - 理解字符串的双重本质
- - '####'
  - 将字符串转换为 Rune
- - '####'
  - 枚举字符串
- - '##'
  - 总结
- - '#'
  - 第 8 章 定义与使用函数
- - '##'
  - 本章准备
- - '##'
  - 定义一个简单函数
- - '###'
  - 定义与使用函数参数
- - '##'
  - 省略参数类型
- - '##'
  - 省略参数名称
- - '###'
  - 定义可变参数
- - '##'
  - 处理可变参数无参数的情况
- - '##'
  - 使用切片作为可变参数的值
- - '###'
  - 使用指针作为函数参数
- - '##'
  - 定义和使用函数返回值
- - '###'
  - 返回多个函数返回值
- - '###'
  - 使用多个结果而非多重含义
- - '###'
  - 使用命名结果
- - '###'
  - 使用空白标识符丢弃结果
- - '###'
  - 使用 `defer` 关键字
- - '##'
  - 本章小结
- - '#'
  - 第 9 章 使用函数类型
- - '##'
  - 本章准备工作
- - '###'
  - 理解函数类型
- - '##'
  - 理解函数比较与零值类型
- - '##'
  - 将函数用作参数
- - '###'
  - 使用函数作为结果
- - '##'
  - 创建函数类型别名
- - '##'
  - 使用函数字面量语法
- - '###'
  - 理解函数变量作用域
- - '###'
  - command-line-arguments
- - '###'
  - 直接使用函数值
- - '###'
  - 理解函数闭包
- - '###'
  - 工厂函数签名
- - '###'
  - 通用代码
- - '###'
  - 函数闭包
- - '###'
  - 理解闭包的求值时机
- - '###'
  - 强制提前求值
- - '###'
  - 闭包指针以防止过早求值
- - '##'
  - 本章小结
- - '#'
  - 第 10 章 定义结构体
- - '##'
  - 本章准备
- - '##'
  - 定义和使用结构体
- - '###'
  - 创建结构体值
- - '###'
  - 使用结构体值
- - '###'
  - 部分赋值结构体值
- - '###'
  - 使用字段位置创建结构体值
- - '###'
  - 定义嵌入字段
- - '###'
  - 比较结构体值
- - '####'
  - 结构体类型之间的转换
- - '###'
  - 定义匿名结构体类型
- - '##'
  - 创建包含结构体值的数组、切片和映射
- - '##'
  - 理解结构体与指针
- - '###'
  - 理解结构体指针便捷语法
- - '###'
  - 理解指向值的指针
- - '###'
  - 理解结构体构造函数
- - '###'
  - 为结构体字段使用指针类型
- - '###'
  - 理解指针字段的复制
- - '##'
  - 理解结构体与结构体指针的零值
- - '##'
  - 总结
- - '#'
  - 第 11 章 使用方法和接口
- - '##'
  - 本章准备
- - '##'
  - 定义和使用方法
- - '###'
  - 定义方法参数与返回值
- - '###'
  - 理解方法重载
- - '###'
  - command-line-arguments
- - '###'
  - 理解指针接收者与值接收者
- - '####'
  - 通过接收者类型调用方法
- - '###'
  - 为类型别名定义方法
- - '##'
  - 将类型和方法放在不同文件中
- - '##'
  - 定义和使用接口
- - '###'
  - 定义接口
- - '###'
  - 实现接口
- - '###'
  - 使用接口
- - '####'
  - 在函数中使用接口
- - '####'
  - 为结构体字段使用接口
- - '###'
  - 理解指针方法接收者的影响
- - '##'
  - 比较接口值
- - '##'
  - 执行类型断言
- - '###'
  - 类型断言与类型转换
- - '###'
  - 执行类型断言前进行测试
- - '###'
  - 启用动态类型切换
- - '##'
  - 使用空接口
- - '###'
  - 使用空接口作为函数参数
- - '##'
  - 本章小结
- - '#'
  - 第 12 章 创建和使用包
- - '##'
  - 本章准备
- - '##'
  - 理解模块文件
- - '##'
  - 创建自定义包
- - '###'
  - 注释导出的特性
- - '###'
  - 使用自定义包
- - '###'
  - 理解包访问控制
- - '###'
  - 向包中添加代码文件
- - '###'
  - 处理包名冲突
- - '##'
  - 使用包别名
- - '##'
  - 使用点导入
- - '##'
  - 创建嵌套包
- - '###'
  - 使用包初始化函数
- - '###'
  - 避免多个初始化函数的陷阱
- - '####'
  - 仅为初始化效果而导入包
- - '##'
  - 使用外部包
- - '###'
  - 寻找 Go 包
- - '###'
  - 理解最小版本选择
- - '###'
  - 管理外部包
- - '##'
  - 本章小结
- - '#'
  - 第 13 章 类型与接口组合
- - '##'
  - 本章准备
- - '##'
  - 理解类型组合
- - '###'
  - 定义基类型
- - '####'
  - 定义构造函数
- - '##'
  - 组合类型
- - '###'
  - 创建嵌套类型链
- - '###'
  - 在同一个结构体中使用多个嵌套类型
- - '###'
  - 理解何时不能进行提升
- - '####'
  - 理解提升的二义性
- - '##'
  - 理解组合与接口
- - '###'
  - 使用组合实现接口
- - '####'
  - 理解类型切换的局限性
- - '###'
  - 组合接口
- - '##'
  - 本章小结
- - '#'
  - 第 14 章 使用协程和通道
- - '##'
  - 本章准备
- - '##'
  - 理解 Go 如何执行代码
- - '##'
  - 创建额外的 Goroutine
- - '###'
  - 从 Goroutine 中获取结果
- - '##'
  - 使用通道发送结果
- - '###'
  - 通过通道接收结果
- - '###'
  - 使用适配器异步执行函数
- - '###'
  - 使用通道
- - '###'
  - 协调通道
- - '###'
  - 使用带缓冲的通道
- - '###'
  - 检查通道缓冲区
- - '###'
  - 发送和接收未知数量的值
- - '####'
  - 关闭通道
- - '####'
  - 枚举通道值
- - '###'
  - 限制通道方向
- - '###'
  - concurrency
- - '####'
  - 限制通道参数方向
- - '##'
  - 使用 Select 语句
- - '###'
  - 无阻塞接收
- - '###'
  - 从多通道接收
- - '###'
  - 输出结果
- - '##'
  - 无阻塞发送
- - '##'
  - 发送到多个通道
- - '##'
  - 本章小结
- - '#'
  - 第 15 章 错误处理
- - '##'
  - 本章准备
- - '##'
  - 处理可恢复的错误
- - '###'
  - 生成错误
- - '####'
  - 忽略错误结果
- - '###'
  - 通过通道报告错误
- - '###'
  - 使用错误便捷函数
- - '##'
  - 处理不可恢复的错误
- - '###'
  - 定义恐慌函数和非恐慌函数
- - '###'
  - 从恐慌中恢复
- - '###'
  - 恢复后再次恐慌
- - '###'
  - 从 Go 协程的恐慌中恢复
- - '##'
  - 本章小结
- - '#'
  - 第二部分 使用 Go 标准库
- - '#'
  - 第 16 章 字符串处理与正则表达式
- - '##'
  - 本章准备
- - '###'
  - 处理字符串
- - '##'
  - 比较字符串
- - '##'
  - 使用面向字节的函数
- - '###'
  - 转换字符串大小写
- - '###'
  - 处理字符大小写
- - '###'
  - 检查字符串
- - '####'
  - 使用自定义函数检查字符串
- - '###'
  - 操作字符串
- - '####'
  - 分割字符串
- - '####'
  - 限制结果数量
- - '####'
  - 按空白字符分割
- - '####'
  - 使用自定义函数分割字符串
- - '###'
  - 修剪字符串
- - '####'
  - 修剪空白字符
- - '####'
  - 修剪字符集
- - '####'
  - 修剪子字符串
- - '####'
  - 使用自定义函数进行修剪
- - '###'
  - 修改字符串
- - '####'
  - 使用映射函数修改字符串
- - '####'
  - 使用字符串替换器
- - '###'
  - 构建与生成字符串
- - '###'
  - 构建字符串
- - '##'
  - 使用正则表达式
- - '###'
  - 编译与复用模式
- - '###'
  - 使用正则表达式拆分字符串
- - '###'
  - 使用子表达式
- - '####'
  - 使用命名子表达式
- - '###'
  - 使用正则表达式替换子字符串
- - '####'
  - 用函数替换匹配的内容
- - '##'
  - 本章总结
- - '#'
  - 第 17 章 格式化与扫描字符串
- - '##'
  - 本章准备工作
- - '##'
  - 编写字符串
- - '###'
  - 格式化字符串
- - '##'
  - 理解格式化动词
- - '###'
  - 使用通用格式化动词
- - '###'
  - 控制结构体格式化
- - '###'
  - 格式化数组、切片和映射
- - '###'
  - 使用整数格式化动词
- - '###'
  - 使用浮点数格式化动词
- - '###'
  - 使用字符串和字符格式化动词
- - '###'
  - 使用布尔格式化动词
- - '###'
  - 使用指针格式化动词
- - '##'
  - 扫描字符串
- - '###'
  - 扫描到切片
- - '###'
  - 处理换行符
- - '###'
  - 使用不同的字符串源
- - '###'
  - 使用扫描模板
- - '##'
  - 本章小结
- - '#'
  - 第 18 章 数学函数与数据排序
- - '##'
  - 本章准备工作
- - '##'
  - 使用数字
- - '###'
  - 生成随机数
- - '###'
  - 生成指定范围内的随机数
- - '###'
  - 打乱元素顺序
- - '##'
  - 排序数据
- - '###'
  - 对数字和字符串切片进行排序
- - '###'
  - 排序已排序数据
- - '###'
  - 排序自定义数据类型
- - '###'
  - 使用不同字段进行排序
- - '###'
  - 指定比较函数
- - '##'
  - 本章小结
- - '#'
  - 第 19 章 日期、时间和时段
- - '##'
  - 本章准备
- - '###'
  - 处理日期和时间
- - '##'
  - 表示日期和时间
- - '###'
  - 将时间格式化为字符串
- - '###'
  - 从字符串解析时间值
- - '##'
  - 使用预定义日期布局
- - '###'
  - 指定解析位置
- - '###'
  - 嵌入时区数据库
- - '###'
  - 使用本地位置
- - '###'
  - 直接指定时区
- - '###'
  - 操作时间值
- - '###'
  - 表示持续时间
- - '###'
  - 创建相对于某个时间的持续时间
- - '###'
  - 从字符串创建持续时间
- - '##'
  - 在协程和通道中使用时间特性
- - '###'
  - 让协程休眠
- - '###'
  - 延迟执行函数
- - '###'
  - 接收定时通知
- - '###'
  - 在 Select 语句中将通知用作超时
- - '###'
  - 停止和重置计时器
- - '###'
  - 接收定期通知
- - '##'
  - 总结
- - '#'
  - 第 20 章 读写数据
- - '##'
  - 本章准备
- - '###'
  - 理解读取器与写入器
- - '##'
  - 理解读取器
- - '##'
  - 理解写入器
- - '###'
  - 为读写器使用便捷函数
- - '##'
  - 使用专门的读写器
- - '###'
  - 使用管道
- - '####'
  - 改进示例
- - '###'
  - 连接多个读取器
- - '###'
  - 组合多个写入器
- - '###'
  - 将读取数据回显到写入器
- - '###'
  - 限制读取数据量
- - '##'
  - 数据缓冲
- - '###'
  - 使用额外的带缓冲读取器方法
- - '###'
  - 执行带缓冲写入
- - '##'
  - 使用读写器进行格式化和扫描
- - '###'
  - 从读取器中扫描值
- - '###'
  - 将格式化字符串写入写入器
- - '###'
  - 将替换器与写入器配合使用
- - '##'
  - 总结
- - '#'
  - 第 21 章 处理 JSON 数据
- - '##'
  - 本章准备工作
- - '##'
  - 读取和写入 JSON 数据
- - '###'
  - 编码 JSON 数据
- - '####'
  - 编码数组和切片
- - '####'
  - 编码映射
- - '####'
  - 编码结构体
- - '#####'
  - 理解 JSON 编码中字段提升的影响
- - '####'
  - 自定义结构体的 JSON 编码
- - '#####'
  - 省略字段
- - '###'
  - 省略未赋值的字段
- - '###'
  - 强制字段编码为字符串
- - '##'
  - 编码接口
- - '##'
  - 创建完全自定义的 JSON 编码
- - '###'
  - 解码 JSON 数据
- - '####'
  - 解码数值
- - '####'
  - 为解码指定类型
- - '###'
  - 解码数组
- - '###'
  - 解码映射
- - '###'
  - 解码结构体
- - '###'
  - 禁止未使用的键
- - '###'
  - 使用结构体标签控制解码
- - '###'
  - 创建完全自定义的 JSON 解码器
- - '##'
  - 本章小结
- - '#'
  - 第 22 章 文件处理
- - '##'
  - 本章准备工作
- - '###'
  - 读取文件
- - '##'
  - 使用便捷的读取函数
- - '####'
  - 解码 JSON 数据
- - '###'
  - 使用 File 结构体读取文件
- - '###'
  - 从特定位置读取
- - '##'
  - 写入文件
- - '###'
  - 使用便捷写入函数
- - '###'
  - 使用 File 结构体写入文件
- - '###'
  - 将 JSON 数据写入文件
- - '###'
  - 使用便捷函数创建新文件
- - '###'
  - 处理文件路径
- - '##'
  - 管理文件和目录
- - '###'
  - 表 22-11：用于管理文件和目录的 os 包函数
- - '###'
  - 探索文件系统
- - '###'
  - 判断文件是否存在
- - '###'
  - 使用模式定位文件
- - '###'
  - 处理目录下的所有文件
- - '##'
  - 小结
- - '#'
  - 第 23 章 使用 HTML 与文本模板
- - '##'
  - 本章准备工作
- - '###'
  - 创建 HTML 模板
- - '##'
  - 加载和执行模板
- - '###'
  - 加载多个模板
- - '####'
  - 枚举已加载的模板
- - '####'
  - 查找特定模板
- - '###'
  - 理解模板动作
- - '###'
  - 插入数据值
- - '###'
  - 理解上下文转义
- - '###'
  - 格式化数据值
- - '###'
  - 链式与括号化模板表达式
- - '####'
  - 修剪空白
- - '####'
  - 在模板中使用切片
- - '#####'
  - 使用内置切片函数
- - '####'
  - 条件执行模板内容
- - '###'
  - 使用可选条件动作
- - '###'
  - 创建具名嵌套模板
- - '###'
  - 定义模板块
- - '###'
  - 定义模板函数
- - '###'
  - 禁用函数结果编码
- - '###'
  - 提供对标准库函数的访问
- - '###'
  - 定义模板变量
- - '###'
  - 在 Range 动作中使用模板变量
- - '##'
  - 创建文本模板
- - '##'
  - 本章小结
- - '#'
  - 第 24 章 创建 HTTP 服务器
- - '##'
  - 本章准备
- - '##'
  - 创建简单的 HTTP 服务器
- - '###'
  - 处理 Windows 防火墙权限请求
- - '###'
  - 创建 HTTP 监听器与处理器
- - '###'
  - 检查请求
- - '###'
  - 过滤请求和生成响应
- - '##'
  - 使用响应便利函数
- - '###'
  - 使用便捷的路由处理器
- - '###'
  - 支持 HTTPS 请求
- - '####'
  - 将 HTTP 请求重定向到 HTTPS
- - '##'
  - 创建静态 HTTP 服务器
- - '###'
  - 创建静态文件路由
- - '##'
  - 使用模板生成响应
- - '##'
  - 理解内容类型嗅探
- - '##'
  - 使用 JSON 数据响应
- - '##'
  - 处理表单数据
- - '###'
  - 从请求中读取表单数据
- - '###'
  - 读取多部分表单
- - '###'
  - 在表单中接收多个文件
- - '##'
  - 读取与设置 Cookie
- - '##'
  - 本章小结
- - '#'
  - 第 25 章 创建 HTTP 客户端
- - '##'
  - 本章准备工作
- - '###'
  - 处理 Windows 防火墙权限请求
- - '###'
  - 发送简单 HTTP 请求
- - '##'
  - 发送 POST 请求
- - '####'
  - 使用 Reader 发布表单
- - '####'
  - 理解 Content-Length 标头
- - '###'
  - 配置 HTTP 客户端请求
- - '##'
  - 使用便捷函数创建请求
- - '###'
  - 处理 Cookie
- - '###'
  - 创建独立的客户端和 Cookie Jar
- - '###'
  - 管理重定向
- - '###'
  - 创建多部分表单
- - '##'
  - 总结
- - '#'
  - 第 26 章 使用数据库
- - '##'
  - 本章准备
- - '###'
  - 准备数据库
- - '###'
  - 安装数据库驱动
- - '###'
  - 打开数据库
- - '###'
  - 执行语句和查询
- - '####'
  - 查询多行数据
- - '####'
  - 理解 Scan 方法
- - '####'
  - 理解 SQL 值如何被扫描
- - '#####'
  - 将值扫描至结构体
- - '###'
  - 使用占位符执行语句
- - '###'
  - 执行单行查询
- - '###'
  - 执行其他查询
- - '##'
  - 使用预编译语句
- - '###'
  - 使用事务
- - '###'
  - 使用反射将数据扫描到结构体中
- - '##'
  - 理解反射的缺点
- - '##'
  - 总结
- - '#'
  - 第 27 章 使用反射
- - '##'
  - 准备本章内容
- - '###'
  - 理解反射的必要性
- - '##'
  - 使用反射
- - '###'
  - 使用基本类型特性
- - '###'
  - 使用基本值特性
- - '###'
  - 识别类型
- - '###'
  - 识别字节切片
- - '###'
  - 获取底层值
- - '###'
  - 使用反射设置值
- - '##'
  - 使用一个值设置另一个值
- - '###'
  - 比较值
- - '##'
  - 使用比较便捷函数
- - '##'
  - 转换值
- - '###'
  - 转换数值类型
- - '##'
  - 创建新值
- - '##'
  - 本章小结
- - '#'
  - 第 28 章 使用反射，第二部分
- - '##'
  - 本章准备
- - '##'
  - 使用指针
- - '###'
  - 使用指针值
- - '##'
  - 处理数组与切片类型
- - '##'
  - 处理数组与切片值
- - '###'
  - 枚举切片与数组
- - '###'
  - 从现有切片创建新切片
- - '###'
  - 创建、复制和追加元素到切片
- - '###'
  - 使用映射类型
- - '###'
  - 使用映射值
- - '####'
  - 设置与移除 Map 中的值
- - '####'
  - 创建新的 Map
- - '###'
  - 使用结构体类型
- - '##'
  - 处理嵌套字段
- - '###'
  - 这意味着从 `FieldByIndex()` 方法返回的结果，不能方便地用于后续对该方法的调用。正因如此，我需要使用自己创建的 `int` 切片来跟踪索引，并将其作为清单
    28-16 中 `FieldByIndex()` 方法的参数：
- - '##'
  - 通过名称定位字段
- - '##'
  - 检查结构体标签
- - '##'
  - 创建结构体类型
- - '###'
  - 使用结构体值
- - '##'
  - 设置结构体字段值
- - '##'
  - 总结
- - '#'
  - 第 29 章 使用反射，第 3 部分
- - '##'
  - 准备工作
- - '###'
  - 使用函数类型
- - '###'
  - 使用函数值
- - '##'
  - 创建和调用新的函数类型和值
- - '##'
  - 关于反射创建函数的示例
- - '###'
  - 理解 `makeMapperFunc` 函数
- - '####'
  - 第一步：识别映射函数的类型
- - '####'
  - 第二步：创建包装器的函数类型
- - '####'
  - 第三步：使用 `MakeFunc` 创建包装器函数
- - '####'
  - 结果：类型安全的函数
- - '####'
  - 运行结果
- - '###'
  - 使用方法
- - '##'
  - 调用方法
- - '###'
  - 使用接口
- - '##'
  - 从接口获取底层值
- - '##'
  - 检查接口方法
- - '###'
  - 使用通道类型
- - '###'
  - 使用通道值
- - '##'
  - 创建新的通道类型和值
- - '##'
  - 从多个通道中选择
- - '##'
  - 本章小结
- - '#'
  - 第 30 章 协调 Goroutine
- - '##'
  - 准备工作
- - '###'
  - 使用等待组
- - '####'
  - 避免复制陷阱
- - '###'
  - 使用互斥（Mutual Exclusion）
- - '##'
  - 避免 `Mutex` 陷阱
- - '###'
  - 使用读写互斥锁
- - '###'
  - 使用条件变量协调协程
- - '###'
  - 确保函数只执行一次
- - '###'
  - 使用上下文
- - '####'
  - 取消请求
- - '####'
  - 设置截止时间
- - '####'
  - 提供请求数据
- - '##'
  - 小结
- - '#'
  - 第 31 章 单元测试、基准测试与日志记录
- - '##'
  - 本章准备
- - '##'
  - 使用测试
- - '###'
  - 决定是否使用测试工具
- - '###'
  - 理解测试包访问权限
- - '###'
  - 运行单元测试
- - '####'
  - 为单元测试编写 Mock 对象
- - '####'
  - 运行特定测试
- - '###'
  - 管理测试执行
- - '####'
  - 跳过测试
- - '##'
  - 基准测试代码
- - '###'
  - 从基准测试中移除准备工作
- - '###'
  - 执行子基准测试
- - '###'
  - 记录数据
- - '##'
  - 代码示例与日志记录
- - '###'
  - 创建自定义日志记录器
- - '##'
  - 总结
- - '#'
  - 第三部分 应用 Go
- - '#'
  - 第 32 章 创建 Web 平台
- - '##'
  - 创建项目
- - '##'
  - 创建一些基本平台功能
- - '###'
  - 创建日志系统
- - '###'
  - 创建配置系统
- - '####'
  - 定义配置文件
- - '###'
  - 实现配置接口
- - '###'
  - 使用配置系统
- - '###'
  - 使用依赖注入管理服务
- - '##'
  - 定义服务生命周期
- - '###'
  - 定义内部服务函数
- - '###'
  - 定义服务注册函数
- - '###'
  - 定义服务解析函数
- - '###'
  - 注册和使用服务
- - '####'
  - 添加对调用函数的支持
- - '####'
  - 为结构体字段添加依赖解析支持
- - '##'
  - 本章小结
- - '#'
  - 第 33 章 中间件、模板和处理器
- - '##'
  - 创建请求管道
- - '###'
  - 定义中间件组件接口
- - '###'
  - 创建请求管道
- - '###'
  - 创建基础组件
- - '####'
  - 创建服务中间件组件
- - '####'
  - 创建日志中间件组件
- - '####'
  - 创建错误处理组件
- - '####'
  - 创建静态文件组件
- - '###'
  - 创建占位响应组件
- - '###'
  - 创建 HTTP 服务器
- - '###'
  - 配置应用程序
- - '###'
  - 简化服务解析
- - '##'
  - 创建 HTML 响应
- - '###'
  - 创建布局和模板
- - '###'
  - 实现模板执行
- - '###'
  - 创建并使用模板服务
- - '##'
  - 引入请求处理器
- - '###'
  - 生成 URL 路由
- - '###'
  - 为处理方法准备参数值
- - '###'
  - 将请求匹配到路由
- - '##'
  - 本章小结
- - '#'
  - 第 34 章 操作、会话与授权
- - '##'
  - 引入操作结果
- - '###'
  - 定义通用操作结果
- - '###'
  - 更新占位符以使用操作结果
- - '###'
  - 从模板中调用请求处理器
- - '###'
  - 更新请求处理
- - '###'
  - 配置应用程序
- - '###'
  - 从路由生成 URL
- - '##'
  - 创建 URL 生成器服务
- - '###'
  - 定义别名路由
- - '###'
  - 验证请求数据
- - '##'
  - 执行数据验证
- - '###'
  - 添加会话
- - '###'
  - 延迟写入响应数据
- - '###'
  - 创建会话接口、服务和中间件
- - '###'
  - 创建使用会话的处理程序
- - '###'
  - 配置应用程序
- - '##'
  - 添加用户授权
- - '###'
  - 定义基本授权类型
- - '###'
  - 实现平台接口
- - '###'
  - 实现访问控制
- - '###'
  - 实现应用程序占位功能
- - '###'
  - 创建认证处理器
- - '###'
  - 配置应用程序
- - '##'
  - 总结
- - '#'
  - 第 35 章 SportsStore：一个真实的应用程序
- - '##'
  - 创建 SportsStore 项目
- - '###'
  - 配置应用程序
- - '###'
  - 启动数据模型
- - '##'
  - 定义仓储接口
- - '##'
  - 实现（临时）仓储
- - '###'
  - 显示产品列表
- - '##'
  - 创建模板和布局
- - '###'
  - 配置应用程序
- - '##'
  - 添加分页功能
- - '##'
  - 样式化模板内容
- - '###'
  - 安装 Bootstrap CSS 文件
- - '###'
  - 更新布局
- - '###'
  - 样式化模板内容
- - '###'
  - 添加对类别筛选的支持
- - '##'
  - 更新请求处理器
- - '##'
  - 创建类别处理器
- - '##'
  - 在产品列表模板中显示类别导航
- - '###'
  - 注册处理器与更新别名
- - '##'
  - 本章小结
- - '#'
  - 第 36 章 SportsStore：购物车与数据库
- - '##'
  - 构建购物车
- - '###'
  - 定义购物车模型与仓库
- - '###'
  - 创建购物车请求处理器
- - '###'
  - 将产品添加到购物车
- - '###'
  - 配置应用程序
- - '###'
  - 添加购物车摘要组件
- - '####'
  - 调用处理器并添加 CSS 图标样式表
- - '##'
  - 使用数据库存储库
- - '###'
  - 创建存储库类型
- - '###'
  - 打开数据库并加载 SQL 命令
- - '###'
  - 定义种子与初始化语句
- - '###'
  - 定义基本查询
- - '####'
  - 为基本查询定义 SQL 文件
- - '###'
  - 定义分页查询
- - '###'
  - 定义 SQL 仓库服务
- - '###'
  - 配置应用程序以使用 SQL 仓库
- - '##'
  - 总结
- - '#'
  - 第 37 章 SportsStore：结账与管理
- - '##'
  - 创建结账流程
- - '###'
  - 定义模型
- - '###'
  - 扩展仓储
- - '###'
  - 禁用临时仓储
- - '###'
  - 定义仓储方法和命令
- - '###'
  - 定义 SQL 文件
- - '##'
  - 实现存储库方法
- - '##'
  - 创建请求处理器和模板
- - '###'
  - 集成结账流程
- - '###'
  - 注册请求处理器
- - '##'
  - 创建管理功能
- - '###'
  - 创建产品管理功能
- - '###'
  - 扩展仓库
- - '###'
  - 实现产品请求处理器
- - '###'
  - 创建分类管理功能
- - '###'
  - 扩展仓储接口
- - '###'
  - 实现类别请求处理程序
- - '##'
  - 总结
- - '#'
  - 第 38 章 SportsStore：收尾与部署
- - '##'
  - 完成管理功能
- - '###'
  - 扩展仓储
- - '###'
  - 实现请求处理器
- - '###'
  - 创建模板
- - '##'
  - 限制对管理功能的访问
- - '###'
  - 创建用户存储和请求处理器
- - '###'
  - 配置应用程序
- - '##'
  - 创建 Web 服务
- - '##'
  - 为部署做准备
- - '###'
  - 安装证书
- - '###'
  - 配置应用程序
- - '###'
  - 构建应用程序
- - '###'
  - 安装 Docker Desktop
- - '###'
  - 创建 Docker 配置文件
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
