name: Web Development with Go
name_cn: Go Web 开发
slug: web-development-with-go
toc:
- - '#'
  - 用 Go 进行 Web 开发
- - '#'
  - 引言
- - '#'
  - Go 编程语言概述
- - '#'
  - 目录
- - '##'
  - 第 1 章：Go 入门 (15)
- - '##'
  - 第 2 章：Go 基础 (15)
- - '##'
  - 第 3 章：用户定义类型与并发 (35)
- - '##'
  - 第 4 章：Web 开发入门 (59)
- - '##'
  - 第 5 章：使用 Go 模板 (79)
- - '##'
  - 第 6 章：HTTP 中间件 (99)
- - '##'
  - 第 7 章：Web 应用身份验证 (121)
- - '##'
  - 第 8 章：使用 MongoDB 持久化 (141)
- - '##'
  - 第 9 章：构建 RESTful 服务 (159)
- - '##'
  - 第 10 章：测试 Go 应用 (211)
- - '##'
  - 第 11 章：在 Google Cloud 上构建 Go Web 应用 (251)
- - '##'
  - 索引 (285)
- - '##'
  - 内容概览
- - '##'
  - 关于作者与技术审校
- - '##'
  - 第 1 章：开始使用 Go
- - '###'
  - 认识 Go
- - '####'
  - 简约务实的设计语言
- - '####'
  - 兼具高生产力的静态类型语言
- - '####'
  - 并发是语言层面的内置特性
- - '####'
  - Go 编译程序速度快
- - '####'
  - Go 是一种通用语言
- - '###'
  - Go 生态系统
- - '###'
  - 安装 Go 工具
- - '####'
  - 检查安装
- - '###'
  - 设置工作环境
- - '####'
  - Go 工作区
- - '####'
  - '`GOPATH` 环境变量'
- - '####'
  - 代码组织路径
- - '###'
  - 编写 Go 程序
- - '####'
  - 编写 Hello World 程序
- - '####'
  - 编写一个库
- - '###'
  - 测试 Go 代码
- - '###'
  - 使用 Go Playground
- - '###'
  - 使用 Go Mobile
- - '###'
  - Go 作为 Web 和微服务语言
- - '###'
  - 使用 Go 语言的微服务架构
- - '###'
  - 本章摘要
- - '##'
  - 第 2 章：Go 语言基础
- - '###'
  - 包
- - '####'
  - 包 main
- - '####'
  - 包别名
- - '####'
  - 函数 init
- - '####'
  - 使用空白标识符
- - '####'
  - 导入包
- - '####'
  - 安装第三方包
- - '####'
  - 编写包
- - '###'
  - Go 工具
- - '####'
  - 格式化 Go 代码
- - '####'
  - Go 文档
- - '###'
  - 处理集合
- - '###'
  - 数组
- - '###'
  - 切片
- - '####'
  - 使用 `make` 函数创建切片
- - '####'
  - 使用切片字面量创建切片
- - '####'
  - 切片函数
- - '####'
  - 长度与容量
- - '####'
  - 遍历切片
- - '###'
  - 映射
- - '###'
  - Defer、Panic 和 Recover
- - '####'
  - Defer
- - '####'
  - Panic
- - '####'
  - Recover
- - '###'
  - 错误处理
- - '###'
  - 总结
- - '##'
  - 第 3 章：用户定义类型与并发
- - '###'
  - 使用结构体定义用户定义类型
- - '####'
  - 创建结构体类型
- - '####'
  - 创建结构体类型的实例
- - '####'
  - 向结构体类型添加行为
- - '####'
  - 调用结构体方法
- - '####'
  - 指针方法接收器
- - '###'
  - 类型组合
- - '###'
  - 覆盖嵌入类型的方法
- - '###'
  - 使用接口
- - '###'
  - 并发
- - '###'
  - Goroutine（协程）
- - '###'
  - GOMAXPROCS 与并行性
- - '###'
  - 通道
- - '####'
  - 无缓冲通道
- - '####'
  - 缓冲通道
- - '###'
  - 总结
- - '##'
  - 第 4 章：Web 开发入门
- - '###'
  - '`net/http` 包'
- - '###'
  - 处理 HTTP 请求
- - '###'
  - ServeMux
- - '###'
  - Handler
- - '###'
  - 构建静态 Web 服务器
- - '###'
  - 创建自定义处理器
- - '###'
  - 使用函数作为处理器
- - '####'
  - '`http.HandlerFunc` 类型'
- - '####'
  - ServeMux.HandleFunc 函数
- - '####'
  - DefaultServeMux
- - '####'
  - '`http.Server` 结构体'
- - '###'
  - Gorilla Mux
- - '###'
  - 构建 RESTful API
- - '####'
  - 数据模型与数据存储
- - '####'
  - 配置复用器
- - '####'
  - 用于 CRUD 操作的处理函数
- - '###'
  - 摘要
- - '##'
  - 第 5 章：使用 Go 模板
- - '###'
  - '`text/template` 包'
- - '####'
  - 使用 `text/template`
- - '####'
  - 定义命名模板
- - '####'
  - 声明变量
- - '####'
  - 使用管道
- - '###'
  - 使用 `html/template` 构建 HTML 视图
- - '####'
  - 构建一个 Web 应用
- - '####'
  - 数据结构与数据存储
- - '####'
  - main 函数
- - '####'
  - 视图与模板定义文件
- - '####'
  - 初始化视图模板
- - '####'
  - 渲染索引页面
- - '####'
  - 渲染添加页面
- - '####'
  - 渲染编辑页面
- - '###'
  - 总结
- - '##'
  - 第 6 章：HTTP 中间件
- - '###'
  - HTTP 中间件简介
- - '###'
  - 编写 HTTP 中间件
- - '####'
  - 如何编写 HTTP 中间件
- - '####'
  - 编写日志记录中间件
- - '####'
  - 控制 HTTP 中间件的执行流
- - '###'
  - 使用第三方中间件
- - '####'
  - 使用 Gorilla Handlers
- - '#####'
  - 安装 Gorilla Handlers
- - '#####'
  - 使用 Gorilla Handlers
- - '####'
  - 使用 Alice 包进行中间件链式调用
- - '#####'
  - 安装 Alice
- - '#####'
  - 使用 Alice
- - '###'
  - 使用 Negroni 包处理中间件
- - '####'
  - Negroni 入门
- - '####'
  - 安装 Negroni
- - '####'
  - 使用 Negroni 进行路由
- - '####'
  - 注册中间件
- - '####'
  - 为特定路由注册中间件
- - '####'
  - 使用 Negroni 中间件栈
- - '###'
  - 在中间件之间共享值
- - '####'
  - 使用 Gorilla Context
- - '####'
  - 使用 Gorilla Context 设置和获取值
- - '###'
  - 总结
- - '##'
  - 第 7 章：为 Web 应用添加身份验证
- - '###'
  - 身份验证与授权
- - '###'
  - 身份验证方法
- - '####'
  - 基于 Cookie 的身份验证
- - '####'
  - 基于令牌的身份验证
- - '###'
  - 使用 OAuth 2 进行身份验证
- - '####'
  - 理解 OAuth 2
- - '####'
  - 使用 Goth 包通过 OAuth 2 进行身份验证
- - '###'
  - 使用 JSON Web Token 进行身份验证
- - '###'
  - 使用 `jwt-go` 包处理 JWT
- - '####'
  - 生成 JWT 令牌
- - '####'
  - 验证 JWT 令牌
- - '####'
  - 运行与测试 API 服务器
- - '####'
  - 使用 HTTP 中间件验证 JWT 令牌
- - '###'
  - 摘要
- - '##'
  - 第 8 章：使用 MongoDB 进行持久化
- - '###'
  - MongoDB 简介
- - '###'
  - MongoDB 入门
- - '####'
  - MongoDB 的 `mgo` 驱动程序简介
- - '#####'
  - 安装 `mgo`
- - '####'
  - 连接到 MongoDB
- - '####'
  - 访问集合
- - '###'
  - MongoDB 的 CRUD 操作
- - '####'
  - 插入文档
- - '#####'
  - 插入结构体值
- - '#####'
  - 插入嵌入式文档
- - '####'
  - 读取文档
- - '#####'
  - 检索所有记录
- - '#####'
  - 排序记录
- - '#####'
  - 检索单条记录
- - '####'
  - 更新文档
- - '####'
  - 删除文档
- - '###'
  - MongoDB 中的索引
- - '###'
  - 管理会话
- - '###'
  - 总结
- - '##'
  - 第 9 章：构建 RESTful 服务
- - '###'
  - RESTful API：数字化转型的基石
- - '####'
  - 使用 RESTful API 进行 API 驱动开发
- - '###'
  - Go：构建 RESTful 服务的绝佳技术栈
- - '####'
  - Go：微服务架构的伟大技术栈
- - '#####'
  - 微服务架构中的 RESTful 服务
- - '####'
  - 构建 RESTful API
- - '#####'
  - 第三方包
- - '#####'
  - 应用结构
- - '#####'
  - 数据模型
- - '#####'
  - RESTful API 的资源建模
- - '######'
  - 将资源映射到应用路由
- - '######'
  - 用户资源的路由
- - '######'
  - 任务资源的路由
- - '#####'
  - 添加路由特定中间件
- - '######'
  - TaskNote 资源的路由
- - '######'
  - 初始化 RESTful API 的路由
- - '#####'
  - 设置 RESTful API 应用
- - '######'
  - 初始化配置值
- - '######'
  - 加载私钥/公钥 RSA 密钥
- - '######'
  - 创建 MongoDB 会话对象
- - '######'
  - 向 MongoDB 添加索引
- - '#####'
  - '`common` 包中的初始化逻辑'
- - '#####'
  - 启动 HTTP 服务器
- - '###'
  - 认证
- - '####'
  - 生成和验证 JWT
- - '#####'
  - 生成 JWT
- - '#####'
  - 向服务器发送 JWT
- - '#####'
  - 授权 JWT
- - '####'
  - 应用程序处理程序
- - '#####'
  - 用于显示 HTTP 错误的辅助函数
- - '#####'
  - 处理 HTTP 请求生命周期中的数据
- - '####'
  - 用户资源的处理程序
- - '#####'
  - JSON 资源模型
- - '#####'
  - 用户资源的处理函数
- - '#####'
  - 注册新用户
- - '#####'
  - 登录系统
- - '#####'
  - 使用 MongoDB 实现数据持久化
- - '####'
  - Tasks 资源的处理器
- - '#####'
  - JSON 资源模型
- - '#####'
  - Tasks 资源的处理函数
- - '#####'
  - 测试 Tasks 资源的 API 操作
- - '####'
  - Notes 资源的处理程序
- - '#####'
  - JSON 资源模型
- - '###'
  - 使用 `godep` 管理 Go 依赖
- - '####'
  - 安装 `godep` 工具
- - '####'
  - 在 TaskManager 中使用 `godep`
- - '####'
  - 恢复应用的依赖关系
- - '###'
  - 使用 Docker 部署 HTTP 服务器
- - '####'
  - Docker 简介：容器化应用平台
- - '####'
  - 编写 Dockerfile
- - '#####'
  - 使用 golang 镜像，其中工作空间（GOPATH）配置在 /go 下。
- - '#####'
  - 将本地包文件复制到容器的工作空间。
- - '#####'
  - 设置工作目录
- - '#####'
  - 获取 godeps 用于管理和恢复依赖项
- - '#####'
  - 恢复 godep 依赖项
- - '#####'
  - 在容器内构建 taskmanager 命令。
- - '#####'
  - 容器启动时运行 taskmanager 命令。
- - '#####'
  - 服务监听 8080 端口。
- - '###'
  - Go Web 框架
- - '###'
  - 总结
- - '###'
  - 参考资料
- - '##'
  - 第 10 章：测试 Go 应用
- - '###'
  - 单元测试
- - '###'
  - 测试驱动开发（TDD）
- - '###'
  - 使用 Go 进行单元测试
- - '####'
  - 编写单元测试
- - '####'
  - 获取测试覆盖率
- - '#####'
  - 基准单元测试
- - '#####'
  - 验证示例代码
- - '####'
  - 跳过测试用例
- - '####'
  - 并行运行测试用例
- - '####'
  - 将测试放入单独的包
- - '###'
  - 测试 Web 应用程序
- - '####'
  - 使用 `ResponseRecorder` 进行测试
- - '###'
  - 使用服务器进行测试
- - '###'
  - Go 语言中的 BDD 测试
- - '####'
  - 行为驱动开发 (BDD)
- - '####'
  - 使用 Ginkgo 进行行为驱动开发
- - '#####'
  - 重构 HTTP API
- - '#####'
  - 编写 BDD 风格的测试
- - '######'
  - 安装 Ginkgo 和 Gomega
- - '######'
  - 引导测试套件
- - '######'
  - 向套件中添加规格测试
- - '######'
  - 使用容器组织规格测试
- - '######'
  - 在测试文件中编写规格
- - '######'
  - 运行规格说明
- - '###'
  - 总结
- - '##'
  - 第 11 章：在谷歌云上构建 Go Web 应用程序
- - '###'
  - 云计算简介
- - '####'
  - 基础设施即服务 (IaaS)
- - '####'
  - 平台即服务 (PaaS)
- - '####'
  - 容器即服务 (CaaS)
- - '###'
  - Google Cloud 简介
- - '###'
  - Google App Engine (GAE)
- - '####'
  - App Engine 的云服务
- - '#####'
  - 用户身份验证
- - '#####'
  - Cloud Datastore
- - '#####'
  - Cloud Bigtable
- - '#####'
  - Google Cloud SQL
- - '#####'
  - Memcache
- - '#####'
  - 搜索
- - '#####'
  - 流量分配
- - '####'
  - 日志记录
- - '####'
  - 任务队列
- - '####'
  - 安全扫描
- - '###'
  - 适用于 Go 语言的 Google App Engine
- - '###'
  - Go 开发环境
- - '###'
  - 构建 App Engine 应用程序
- - '####'
  - 编写 HTTP 服务器
- - '####'
  - 创建配置文件
- - '####'
  - 在开发服务器中测试应用
- - '####'
  - 将 App Engine 应用部署到云端
- - '###'
  - 创建混合型独立/App Engine 应用
- - '###'
  - 使用云原生数据库
- - '####'
  - Google Cloud Datastore 简介
- - '#####'
  - 数据存储最重要的事
- - '#####'
  - 实体
- - '#####'
  - 祖先与后代
- - '####'
  - 使用 Cloud Datastore
- - '#####'
  - 创建新实体
- - '#####'
  - 查询 Datastore
- - '#####'
  - 运行应用程序
- - '###'
  - 使用 Cloud Endpoints 构建后端 API
- - '####'
  - 适用于 Go 的 Cloud Endpoints
- - '#####'
  - 安装 endpoints 包
- - '####'
  - 使用 Go 的 Cloud Endpoints 后端 API
- - '####'
  - 运行 Cloud Endpoints 后端 API
- - '####'
  - 生成客户端库
- - '#####'
  - 在 URL 中使用 rpc 后缀
- - '#####'
  - 在 URL 中使用 rest 后缀
- - '###'
  - 总结
- - '###'
  - 参考
- - '##'
  - 索引
- - '###'
  - A
- - '####'
  - Alice 包
- - '####'
  - App Engine 应用配置文件
- - '####'
  - 数组
- - '####'
  - 身份验证
- - '###'
  - B
- - '####'
  - 行为驱动开发 (BDD)
- - '####'
  - 空白标识符
- - '####'
  - BSON / 二进制 JSON (BSON)
- - '####'
  - 缓冲通道
- - '###'
  - C
- - '####'
  - CaaS
- - '####'
  - 云计算
- - '####'
  - 并发
- - '####'
  - 容器即服务 (CaaS)
- - '####'
  - 基于 Cookie 的身份验证
- - '####'
  - CRUD 操作，MongoDB
- - '####'
  - 自定义处理器
- - '###'
  - D
- - '####'
  - 数据集合
- - '####'
  - DefaultServeMux
- - '####'
  - Docker
- - '###'
  - E
- - '####'
  - 嵌入类型
- - '####'
  - 错误处理
- - '###'
  - F
- - '####'
  - 全功能 Web 框架
- - '####'
  - 函数
- - '###'
  - G
- - '####'
  - GAE
- - '####'
  - Ginkgo，BDD 风格测试
- - '####'
  - Godeps
- - '####'
  - '`godoc` 工具'
- - '####'
  - Go 文档
- - '####'
  - Go 生态系统
- - '####'
  - Go 工具
- - '####'
  - '`GOMAXPROCS`'
- - '####'
  - Go Mobile 项目
- - '####'
  - Google App Engine (GAE)
- - '####'
  - Google Cloud Bigtable
- - '####'
  - Google Cloud Datastore
- - '####'
  - Google Cloud Endpoints
- - '####'
  - Google Cloud 平台服务
- - '####'
  - Google Cloud SQL
- - '####'
  - Go 编程语言
- - '####'
  - Go Playground
- - '####'
  - Gorilla 处理器
- - '####'
  - Gorilla Web 工具包
- - '####'
  - Goroutine
- - '####'
  - Go 工具命令
- - '###'
  - H
- - '####'
  - 处理器
- - '####'
  - '`html/template` 包'
- - '####'
  - HTTP 应用程序
- - '####'
  - HTTP 中间件组件
- - '####'
  - HTTP 请求
- - '####'
  - 混合独立/App Engine 应用程序
- - '###'
  - I
- - '####'
  - 基础设施即服务 (IaaS) 模型
- - '####'
  - 接口
- - '###'
  - J, K
- - '####'
  - JSON API
- - '####'
  - JSON Web 令牌 (JWT)
- - '###'
  - L
- - '####'
  - '`ListenAndServe` 签名'
- - '###'
  - M
- - '####'
  - 映射，数据集合
- - '####'
  - 微服务架构
- - '####'
  - MongoDB
- - '####'
  - 单体架构方法
- - '####'
  - 多路复用器配置
- - '###'
  - N
- - '####'
  - Negroni
- - '###'
  - O
- - '####'
  - OAuth 2
- - '####'
  - 面向对象编程 (OOP) 语言
- - '###'
  - P, Q
- - '####'
  - PaaS
- - '####'
  - 包
- - '####'
  - 并行性
- - '####'
  - 平台即服务 (PaaS) 模型
- - '####'
  - 指针方法接收器
- - '###'
  - R
- - '####'
  - RESTful API
- - '###'
  - S
- - '####'
  - '`ServeMux.HandleFunc` 函数'
- - '####'
  - 单页应用 (SPA) 架构
- - '####'
  - 切片
- - '####'
  - 静态类型语言
- - '####'
  - 静态 Web 服务器
- - '####'
  - 结构体
- - '###'
  - T
- - '####'
  - 测试驱动开发 (TDD)
- - '####'
  - '`text/template` 包'
- - '####'
  - 第三方包安装
- - '####'
  - 基于令牌的身份验证
- - '####'
  - 类型组合
- - '###'
  - U
- - '####'
  - 无缓冲通道
- - '####'
  - 统一资源标识符 (URI)
- - '####'
  - 单元测试
- - '###'
  - W, X, Y, Z
- - '####'
  - Web 与微服务
